"""
generated-mcp-server · generated by MCPForge 2.1.0

source API: https://httpbin.org
73 tools total.
Run:
    pip install -r requirements.txt
    fastmcp dev server.py
"""
from __future__ import annotations

import asyncio
import os
import urllib.parse
from typing import Any, Optional

import httpx
from fastmcp import FastMCP

mcp = FastMCP("generated-mcp-server")
BASE_URL = os.getenv("API_BASE_URL", "https://httpbin.org")



_PATH_GET__ABSOLUTE_REDIRECT__N = "/absolute-redirect/{n}"


def _register_get__absolute_redirect__n(mcp: FastMCP) -> None:
    """Call operation get__absolute-redirect_{n} (GET /absolute-redirect/{n})."""

    @mcp.tool()
    async def get__absolute_redirect__n(n: int) -> dict:
        """Absolutely 302 Redirects n times."""
        url = BASE_URL.rstrip("/") + _PATH_GET__ABSOLUTE_REDIRECT__N
        url = url.replace("{n}", urllib.parse.quote(str(n)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_DELETE__ANYTHING = "/anything"


def _register_delete__anything(mcp: FastMCP) -> None:
    """Call operation delete__anything (DELETE /anything)."""

    @mcp.tool()
    async def delete__anything() -> dict:
        """Returns anything passed in request data."""
        url = BASE_URL.rstrip("/") + _PATH_DELETE__ANYTHING
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.delete(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__ANYTHING = "/anything"


def _register_get__anything(mcp: FastMCP) -> None:
    """Call operation get__anything (GET /anything)."""

    @mcp.tool()
    async def get__anything() -> dict:
        """Returns anything passed in request data."""
        url = BASE_URL.rstrip("/") + _PATH_GET__ANYTHING
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_PATCH__ANYTHING = "/anything"


def _register_patch__anything(mcp: FastMCP) -> None:
    """Call operation patch__anything (PATCH /anything)."""

    @mcp.tool()
    async def patch__anything() -> dict:
        """Returns anything passed in request data."""
        url = BASE_URL.rstrip("/") + _PATH_PATCH__ANYTHING
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.patch(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_POST__ANYTHING = "/anything"


def _register_post__anything(mcp: FastMCP) -> None:
    """Call operation post__anything (POST /anything)."""

    @mcp.tool()
    async def post__anything() -> dict:
        """Returns anything passed in request data."""
        url = BASE_URL.rstrip("/") + _PATH_POST__ANYTHING
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.post(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_PUT__ANYTHING = "/anything"


def _register_put__anything(mcp: FastMCP) -> None:
    """Call operation put__anything (PUT /anything)."""

    @mcp.tool()
    async def put__anything() -> dict:
        """Returns anything passed in request data."""
        url = BASE_URL.rstrip("/") + _PATH_PUT__ANYTHING
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.put(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_DELETE__ANYTHING__ANYTHING = "/anything/{anything}"


def _register_delete__anything__anything(mcp: FastMCP) -> None:
    """Call operation delete__anything_{anything} (DELETE /anything/{anything})."""

    @mcp.tool()
    async def delete__anything__anything(anything: str) -> dict:
        """Returns anything passed in request data."""
        url = BASE_URL.rstrip("/") + _PATH_DELETE__ANYTHING__ANYTHING
        url = url.replace("{anything}", urllib.parse.quote(str(anything)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.delete(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__ANYTHING__ANYTHING = "/anything/{anything}"


def _register_get__anything__anything(mcp: FastMCP) -> None:
    """Call operation get__anything_{anything} (GET /anything/{anything})."""

    @mcp.tool()
    async def get__anything__anything(anything: str) -> dict:
        """Returns anything passed in request data."""
        url = BASE_URL.rstrip("/") + _PATH_GET__ANYTHING__ANYTHING
        url = url.replace("{anything}", urllib.parse.quote(str(anything)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_PATCH__ANYTHING__ANYTHING = "/anything/{anything}"


def _register_patch__anything__anything(mcp: FastMCP) -> None:
    """Call operation patch__anything_{anything} (PATCH /anything/{anything})."""

    @mcp.tool()
    async def patch__anything__anything(anything: str) -> dict:
        """Returns anything passed in request data."""
        url = BASE_URL.rstrip("/") + _PATH_PATCH__ANYTHING__ANYTHING
        url = url.replace("{anything}", urllib.parse.quote(str(anything)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.patch(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_POST__ANYTHING__ANYTHING = "/anything/{anything}"


def _register_post__anything__anything(mcp: FastMCP) -> None:
    """Call operation post__anything_{anything} (POST /anything/{anything})."""

    @mcp.tool()
    async def post__anything__anything(anything: str) -> dict:
        """Returns anything passed in request data."""
        url = BASE_URL.rstrip("/") + _PATH_POST__ANYTHING__ANYTHING
        url = url.replace("{anything}", urllib.parse.quote(str(anything)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.post(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_PUT__ANYTHING__ANYTHING = "/anything/{anything}"


def _register_put__anything__anything(mcp: FastMCP) -> None:
    """Call operation put__anything_{anything} (PUT /anything/{anything})."""

    @mcp.tool()
    async def put__anything__anything(anything: str) -> dict:
        """Returns anything passed in request data."""
        url = BASE_URL.rstrip("/") + _PATH_PUT__ANYTHING__ANYTHING
        url = url.replace("{anything}", urllib.parse.quote(str(anything)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.put(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__BASE64__VALUE = "/base64/{value}"


def _register_get__base64__value(mcp: FastMCP) -> None:
    """Call operation get__base64_{value} (GET /base64/{value})."""

    @mcp.tool()
    async def get__base64__value(value: str) -> dict:
        """Decodes base64url-encoded string."""
        url = BASE_URL.rstrip("/") + _PATH_GET__BASE64__VALUE
        url = url.replace("{value}", urllib.parse.quote(str(value)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__BASIC_AUTH__USER___PASSWD = "/basic-auth/{user}/{passwd}"


def _register_get__basic_auth__user___passwd(mcp: FastMCP) -> None:
    """Call operation get__basic-auth_{user}_{passwd} (GET /basic-auth/{user}/{passwd})."""

    @mcp.tool()
    async def get__basic_auth__user___passwd(user: str, passwd: str) -> dict:
        """Prompts the user for authorization using HTTP Basic Auth."""
        url = BASE_URL.rstrip("/") + _PATH_GET__BASIC_AUTH__USER___PASSWD
        url = url.replace("{user}", urllib.parse.quote(str(user)))
        url = url.replace("{passwd}", urllib.parse.quote(str(passwd)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__BEARER = "/bearer"


def _register_get__bearer(mcp: FastMCP) -> None:
    """Call operation get__bearer (GET /bearer)."""

    @mcp.tool()
    async def get__bearer() -> dict:
        """Prompts the user for authorization using bearer authentication."""
        url = BASE_URL.rstrip("/") + _PATH_GET__BEARER
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__BROTLI = "/brotli"


def _register_get__brotli(mcp: FastMCP) -> None:
    """Call operation get__brotli (GET /brotli)."""

    @mcp.tool()
    async def get__brotli() -> dict:
        """Returns Brotli-encoded data."""
        url = BASE_URL.rstrip("/") + _PATH_GET__BROTLI
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__BYTES__N = "/bytes/{n}"


def _register_get__bytes__n(mcp: FastMCP) -> None:
    """Call operation get__bytes_{n} (GET /bytes/{n})."""

    @mcp.tool()
    async def get__bytes__n(n: int) -> dict:
        """Returns n random bytes generated with given seed"""
        url = BASE_URL.rstrip("/") + _PATH_GET__BYTES__N
        url = url.replace("{n}", urllib.parse.quote(str(n)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__CACHE = "/cache"


def _register_get__cache(mcp: FastMCP) -> None:
    """Call operation get__cache (GET /cache)."""

    @mcp.tool()
    async def get__cache() -> dict:
        """Returns a 304 if an If-Modified-Since header or If-None-Match is present. Returns the same as a GET otherwise."""
        url = BASE_URL.rstrip("/") + _PATH_GET__CACHE
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__CACHE__VALUE = "/cache/{value}"


def _register_get__cache__value(mcp: FastMCP) -> None:
    """Call operation get__cache_{value} (GET /cache/{value})."""

    @mcp.tool()
    async def get__cache__value(value: int) -> dict:
        """Sets a Cache-Control header for n seconds."""
        url = BASE_URL.rstrip("/") + _PATH_GET__CACHE__VALUE
        url = url.replace("{value}", urllib.parse.quote(str(value)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__COOKIES = "/cookies"


def _register_get__cookies(mcp: FastMCP) -> None:
    """Call operation get__cookies (GET /cookies)."""

    @mcp.tool()
    async def get__cookies() -> dict:
        """Returns cookie data."""
        url = BASE_URL.rstrip("/") + _PATH_GET__COOKIES
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__COOKIES_DELETE = "/cookies/delete"


def _register_get__cookies_delete(mcp: FastMCP) -> None:
    """Call operation get__cookies_delete (GET /cookies/delete)."""

    @mcp.tool()
    async def get__cookies_delete(freeform: Optional[str] = None) -> dict:
        """Deletes cookie(s) as provided by the query string and redirects to cookie list."""
        url = BASE_URL.rstrip("/") + _PATH_GET__COOKIES_DELETE
        params: dict[str, Any] = {}
        if freeform is not None:
            params["freeform"] = freeform
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__COOKIES_SET = "/cookies/set"


def _register_get__cookies_set(mcp: FastMCP) -> None:
    """Call operation get__cookies_set (GET /cookies/set)."""

    @mcp.tool()
    async def get__cookies_set(freeform: Optional[str] = None) -> dict:
        """Sets cookie(s) as provided by the query string and redirects to cookie list."""
        url = BASE_URL.rstrip("/") + _PATH_GET__COOKIES_SET
        params: dict[str, Any] = {}
        if freeform is not None:
            params["freeform"] = freeform
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__COOKIES_SET__NAME___VALUE = "/cookies/set/{name}/{value}"


def _register_get__cookies_set__name___value(mcp: FastMCP) -> None:
    """Call operation get__cookies_set_{name}_{value} (GET /cookies/set/{name}/{value})."""

    @mcp.tool()
    async def get__cookies_set__name___value(name: str, value: str) -> dict:
        """Sets a cookie and redirects to cookie list."""
        url = BASE_URL.rstrip("/") + _PATH_GET__COOKIES_SET__NAME___VALUE
        url = url.replace("{name}", urllib.parse.quote(str(name)))
        url = url.replace("{value}", urllib.parse.quote(str(value)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__DEFLATE = "/deflate"


def _register_get__deflate(mcp: FastMCP) -> None:
    """Call operation get__deflate (GET /deflate)."""

    @mcp.tool()
    async def get__deflate() -> dict:
        """Returns Deflate-encoded data."""
        url = BASE_URL.rstrip("/") + _PATH_GET__DEFLATE
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_DELETE__DELAY__DELAY = "/delay/{delay}"


def _register_delete__delay__delay(mcp: FastMCP) -> None:
    """Call operation delete__delay_{delay} (DELETE /delay/{delay})."""

    @mcp.tool()
    async def delete__delay__delay(delay: int) -> dict:
        """Returns a delayed response (max of 10 seconds)."""
        url = BASE_URL.rstrip("/") + _PATH_DELETE__DELAY__DELAY
        url = url.replace("{delay}", urllib.parse.quote(str(delay)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.delete(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__DELAY__DELAY = "/delay/{delay}"


def _register_get__delay__delay(mcp: FastMCP) -> None:
    """Call operation get__delay_{delay} (GET /delay/{delay})."""

    @mcp.tool()
    async def get__delay__delay(delay: int) -> dict:
        """Returns a delayed response (max of 10 seconds)."""
        url = BASE_URL.rstrip("/") + _PATH_GET__DELAY__DELAY
        url = url.replace("{delay}", urllib.parse.quote(str(delay)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_PATCH__DELAY__DELAY = "/delay/{delay}"


def _register_patch__delay__delay(mcp: FastMCP) -> None:
    """Call operation patch__delay_{delay} (PATCH /delay/{delay})."""

    @mcp.tool()
    async def patch__delay__delay(delay: int) -> dict:
        """Returns a delayed response (max of 10 seconds)."""
        url = BASE_URL.rstrip("/") + _PATH_PATCH__DELAY__DELAY
        url = url.replace("{delay}", urllib.parse.quote(str(delay)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.patch(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_POST__DELAY__DELAY = "/delay/{delay}"


def _register_post__delay__delay(mcp: FastMCP) -> None:
    """Call operation post__delay_{delay} (POST /delay/{delay})."""

    @mcp.tool()
    async def post__delay__delay(delay: int) -> dict:
        """Returns a delayed response (max of 10 seconds)."""
        url = BASE_URL.rstrip("/") + _PATH_POST__DELAY__DELAY
        url = url.replace("{delay}", urllib.parse.quote(str(delay)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.post(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_PUT__DELAY__DELAY = "/delay/{delay}"


def _register_put__delay__delay(mcp: FastMCP) -> None:
    """Call operation put__delay_{delay} (PUT /delay/{delay})."""

    @mcp.tool()
    async def put__delay__delay(delay: int) -> dict:
        """Returns a delayed response (max of 10 seconds)."""
        url = BASE_URL.rstrip("/") + _PATH_PUT__DELAY__DELAY
        url = url.replace("{delay}", urllib.parse.quote(str(delay)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.put(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_DELETE__DELETE = "/delete"


def _register_delete__delete(mcp: FastMCP) -> None:
    """Call operation delete__delete (DELETE /delete)."""

    @mcp.tool()
    async def delete__delete() -> dict:
        """The request's DELETE parameters."""
        url = BASE_URL.rstrip("/") + _PATH_DELETE__DELETE
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.delete(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__DENY = "/deny"


def _register_get__deny(mcp: FastMCP) -> None:
    """Call operation get__deny (GET /deny)."""

    @mcp.tool()
    async def get__deny() -> dict:
        """Returns page denied by robots.txt rules."""
        url = BASE_URL.rstrip("/") + _PATH_GET__DENY
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__DIGEST_AUTH__QOP___USER___PASSWD = "/digest-auth/{qop}/{user}/{passwd}"


def _register_get__digest_auth__qop___user___passwd(mcp: FastMCP) -> None:
    """Call operation get__digest-auth_{qop}_{user}_{passwd} (GET /digest-auth/{qop}/{user}/{passwd})."""

    @mcp.tool()
    async def get__digest_auth__qop___user___passwd(qop: str, user: str, passwd: str) -> dict:
        """Prompts the user for authorization using Digest Auth."""
        url = BASE_URL.rstrip("/") + _PATH_GET__DIGEST_AUTH__QOP___USER___PASSWD
        url = url.replace("{qop}", urllib.parse.quote(str(qop)))
        url = url.replace("{user}", urllib.parse.quote(str(user)))
        url = url.replace("{passwd}", urllib.parse.quote(str(passwd)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__DIGEST_AUTH__QOP___USER___PASSWD___ALGORITHM = "/digest-auth/{qop}/{user}/{passwd}/{algorithm}"


def _register_get__digest_auth__qop___user___passwd___algorithm(mcp: FastMCP) -> None:
    """Call operation get__digest-auth_{qop}_{user}_{passwd}_{algorithm} (GET /digest-auth/{qop}/{user}/{passwd}/{algorithm})."""

    @mcp.tool()
    async def get__digest_auth__qop___user___passwd___algorithm(qop: str, user: str, passwd: str, algorithm: str) -> dict:
        """Prompts the user for authorization using Digest Auth + Algorithm."""
        url = BASE_URL.rstrip("/") + _PATH_GET__DIGEST_AUTH__QOP___USER___PASSWD___ALGORITHM
        url = url.replace("{qop}", urllib.parse.quote(str(qop)))
        url = url.replace("{user}", urllib.parse.quote(str(user)))
        url = url.replace("{passwd}", urllib.parse.quote(str(passwd)))
        url = url.replace("{algorithm}", urllib.parse.quote(str(algorithm)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__DIGEST_AUTH__QOP___USER___PASSWD___ALGORITHM___STALE_AFTER = "/digest-auth/{qop}/{user}/{passwd}/{algorithm}/{stale_after}"


def _register_get__digest_auth__qop___user___passwd___algorithm___stale_after(mcp: FastMCP) -> None:
    """Call operation get__digest-auth_{qop}_{user}_{passwd}_{algorithm}_{stale_after} (GET /digest-auth/{qop}/{user}/{passwd}/{algorithm}/{stale_after})."""

    @mcp.tool()
    async def get__digest_auth__qop___user___passwd___algorithm___stale_after(qop: str, user: str, passwd: str, algorithm: str, stale_after: str) -> dict:
        """Prompts the user for authorization using Digest Auth + Algorithm."""
        url = BASE_URL.rstrip("/") + _PATH_GET__DIGEST_AUTH__QOP___USER___PASSWD___ALGORITHM___STALE_AFTER
        url = url.replace("{qop}", urllib.parse.quote(str(qop)))
        url = url.replace("{user}", urllib.parse.quote(str(user)))
        url = url.replace("{passwd}", urllib.parse.quote(str(passwd)))
        url = url.replace("{algorithm}", urllib.parse.quote(str(algorithm)))
        url = url.replace("{stale_after}", urllib.parse.quote(str(stale_after)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__DRIP = "/drip"


def _register_get__drip(mcp: FastMCP) -> None:
    """Call operation get__drip (GET /drip)."""

    @mcp.tool()
    async def get__drip(duration: Optional[float] = None, numbytes: Optional[int] = None, code: Optional[int] = None, delay: Optional[float] = None) -> dict:
        """Drips data over a duration after an optional initial delay."""
        url = BASE_URL.rstrip("/") + _PATH_GET__DRIP
        params: dict[str, Any] = {}
        if duration is not None:
            params["duration"] = duration
        if numbytes is not None:
            params["numbytes"] = numbytes
        if code is not None:
            params["code"] = code
        if delay is not None:
            params["delay"] = delay
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__ENCODING_UTF8 = "/encoding/utf8"


def _register_get__encoding_utf8(mcp: FastMCP) -> None:
    """Call operation get__encoding_utf8 (GET /encoding/utf8)."""

    @mcp.tool()
    async def get__encoding_utf8() -> dict:
        """Returns a UTF-8 encoded body."""
        url = BASE_URL.rstrip("/") + _PATH_GET__ENCODING_UTF8
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__ETAG__ETAG = "/etag/{etag}"


def _register_get__etag__etag(mcp: FastMCP) -> None:
    """Call operation get__etag_{etag} (GET /etag/{etag})."""

    @mcp.tool()
    async def get__etag__etag(etag: str) -> dict:
        """Assumes the resource has the given etag and responds to If-None-Match and If-Match headers appropriately."""
        url = BASE_URL.rstrip("/") + _PATH_GET__ETAG__ETAG
        url = url.replace("{etag}", urllib.parse.quote(str(etag)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__GET = "/get"


def _register_get__get(mcp: FastMCP) -> None:
    """Call operation get__get (GET /get)."""

    @mcp.tool()
    async def get__get() -> dict:
        """The request's query parameters."""
        url = BASE_URL.rstrip("/") + _PATH_GET__GET
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__GZIP = "/gzip"


def _register_get__gzip(mcp: FastMCP) -> None:
    """Call operation get__gzip (GET /gzip)."""

    @mcp.tool()
    async def get__gzip() -> dict:
        """Returns GZip-encoded data."""
        url = BASE_URL.rstrip("/") + _PATH_GET__GZIP
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__HEADERS = "/headers"


def _register_get__headers(mcp: FastMCP) -> None:
    """Call operation get__headers (GET /headers)."""

    @mcp.tool()
    async def get__headers() -> dict:
        """Return the incoming request's HTTP headers."""
        url = BASE_URL.rstrip("/") + _PATH_GET__HEADERS
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__HIDDEN_BASIC_AUTH__USER___PASSWD = "/hidden-basic-auth/{user}/{passwd}"


def _register_get__hidden_basic_auth__user___passwd(mcp: FastMCP) -> None:
    """Call operation get__hidden-basic-auth_{user}_{passwd} (GET /hidden-basic-auth/{user}/{passwd})."""

    @mcp.tool()
    async def get__hidden_basic_auth__user___passwd(user: str, passwd: str) -> dict:
        """Prompts the user for authorization using HTTP Basic Auth."""
        url = BASE_URL.rstrip("/") + _PATH_GET__HIDDEN_BASIC_AUTH__USER___PASSWD
        url = url.replace("{user}", urllib.parse.quote(str(user)))
        url = url.replace("{passwd}", urllib.parse.quote(str(passwd)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__HTML = "/html"


def _register_get__html(mcp: FastMCP) -> None:
    """Call operation get__html (GET /html)."""

    @mcp.tool()
    async def get__html() -> dict:
        """Returns a simple HTML document."""
        url = BASE_URL.rstrip("/") + _PATH_GET__HTML
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__IMAGE = "/image"


def _register_get__image(mcp: FastMCP) -> None:
    """Call operation get__image (GET /image)."""

    @mcp.tool()
    async def get__image() -> dict:
        """Returns a simple image of the type suggest by the Accept header."""
        url = BASE_URL.rstrip("/") + _PATH_GET__IMAGE
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__IMAGE_JPEG = "/image/jpeg"


def _register_get__image_jpeg(mcp: FastMCP) -> None:
    """Call operation get__image_jpeg (GET /image/jpeg)."""

    @mcp.tool()
    async def get__image_jpeg() -> dict:
        """Returns a simple JPEG image."""
        url = BASE_URL.rstrip("/") + _PATH_GET__IMAGE_JPEG
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__IMAGE_PNG = "/image/png"


def _register_get__image_png(mcp: FastMCP) -> None:
    """Call operation get__image_png (GET /image/png)."""

    @mcp.tool()
    async def get__image_png() -> dict:
        """Returns a simple PNG image."""
        url = BASE_URL.rstrip("/") + _PATH_GET__IMAGE_PNG
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__IMAGE_SVG = "/image/svg"


def _register_get__image_svg(mcp: FastMCP) -> None:
    """Call operation get__image_svg (GET /image/svg)."""

    @mcp.tool()
    async def get__image_svg() -> dict:
        """Returns a simple SVG image."""
        url = BASE_URL.rstrip("/") + _PATH_GET__IMAGE_SVG
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__IMAGE_WEBP = "/image/webp"


def _register_get__image_webp(mcp: FastMCP) -> None:
    """Call operation get__image_webp (GET /image/webp)."""

    @mcp.tool()
    async def get__image_webp() -> dict:
        """Returns a simple WEBP image."""
        url = BASE_URL.rstrip("/") + _PATH_GET__IMAGE_WEBP
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__IP = "/ip"


def _register_get__ip(mcp: FastMCP) -> None:
    """Call operation get__ip (GET /ip)."""

    @mcp.tool()
    async def get__ip() -> dict:
        """Returns the requester's IP Address."""
        url = BASE_URL.rstrip("/") + _PATH_GET__IP
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__JSON = "/json"


def _register_get__json(mcp: FastMCP) -> None:
    """Call operation get__json (GET /json)."""

    @mcp.tool()
    async def get__json() -> dict:
        """Returns a simple JSON document."""
        url = BASE_URL.rstrip("/") + _PATH_GET__JSON
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__LINKS__N___OFFSET = "/links/{n}/{offset}"


def _register_get__links__n___offset(mcp: FastMCP) -> None:
    """Call operation get__links_{n}_{offset} (GET /links/{n}/{offset})."""

    @mcp.tool()
    async def get__links__n___offset(n: int, offset: int) -> dict:
        """Generate a page containing n links to other pages which do the same."""
        url = BASE_URL.rstrip("/") + _PATH_GET__LINKS__N___OFFSET
        url = url.replace("{n}", urllib.parse.quote(str(n)))
        url = url.replace("{offset}", urllib.parse.quote(str(offset)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_PATCH__PATCH = "/patch"


def _register_patch__patch(mcp: FastMCP) -> None:
    """Call operation patch__patch (PATCH /patch)."""

    @mcp.tool()
    async def patch__patch() -> dict:
        """The request's PATCH parameters."""
        url = BASE_URL.rstrip("/") + _PATH_PATCH__PATCH
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.patch(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_POST__POST = "/post"


def _register_post__post(mcp: FastMCP) -> None:
    """Call operation post__post (POST /post)."""

    @mcp.tool()
    async def post__post() -> dict:
        """The request's POST parameters."""
        url = BASE_URL.rstrip("/") + _PATH_POST__POST
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.post(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_PUT__PUT = "/put"


def _register_put__put(mcp: FastMCP) -> None:
    """Call operation put__put (PUT /put)."""

    @mcp.tool()
    async def put__put() -> dict:
        """The request's PUT parameters."""
        url = BASE_URL.rstrip("/") + _PATH_PUT__PUT
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.put(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__RANGE__NUMBYTES = "/range/{numbytes}"


def _register_get__range__numbytes(mcp: FastMCP) -> None:
    """Call operation get__range_{numbytes} (GET /range/{numbytes})."""

    @mcp.tool()
    async def get__range__numbytes(numbytes: int) -> dict:
        """Streams n random bytes generated with given seed, at given chunk size per packet."""
        url = BASE_URL.rstrip("/") + _PATH_GET__RANGE__NUMBYTES
        url = url.replace("{numbytes}", urllib.parse.quote(str(numbytes)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_DELETE__REDIRECT_TO = "/redirect-to"


def _register_delete__redirect_to(mcp: FastMCP) -> None:
    """Call operation delete__redirect-to (DELETE /redirect-to)."""

    @mcp.tool()
    async def delete__redirect_to() -> dict:
        """302/3XX Redirects to the given URL."""
        url = BASE_URL.rstrip("/") + _PATH_DELETE__REDIRECT_TO
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.delete(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__REDIRECT_TO = "/redirect-to"


def _register_get__redirect_to(mcp: FastMCP) -> None:
    """Call operation get__redirect-to (GET /redirect-to)."""

    @mcp.tool()
    async def get__redirect_to(url: Optional[str] = None, status_code: Optional[int] = None) -> dict:
        """302/3XX Redirects to the given URL."""
        url = BASE_URL.rstrip("/") + _PATH_GET__REDIRECT_TO
        params: dict[str, Any] = {}
        if url is not None:
            params["url"] = url
        if status_code is not None:
            params["status_code"] = status_code
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_PATCH__REDIRECT_TO = "/redirect-to"


def _register_patch__redirect_to(mcp: FastMCP) -> None:
    """Call operation patch__redirect-to (PATCH /redirect-to)."""

    @mcp.tool()
    async def patch__redirect_to() -> dict:
        """302/3XX Redirects to the given URL."""
        url = BASE_URL.rstrip("/") + _PATH_PATCH__REDIRECT_TO
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.patch(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_POST__REDIRECT_TO = "/redirect-to"


def _register_post__redirect_to(mcp: FastMCP) -> None:
    """Call operation post__redirect-to (POST /redirect-to)."""

    @mcp.tool()
    async def post__redirect_to(body: Optional[dict] = None) -> dict:
        """302/3XX Redirects to the given URL."""
        url = BASE_URL.rstrip("/") + _PATH_POST__REDIRECT_TO
        params: dict[str, Any] = {}
        json_body = body
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.post(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_PUT__REDIRECT_TO = "/redirect-to"


def _register_put__redirect_to(mcp: FastMCP) -> None:
    """Call operation put__redirect-to (PUT /redirect-to)."""

    @mcp.tool()
    async def put__redirect_to(body: Optional[dict] = None) -> dict:
        """302/3XX Redirects to the given URL."""
        url = BASE_URL.rstrip("/") + _PATH_PUT__REDIRECT_TO
        params: dict[str, Any] = {}
        json_body = body
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.put(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__REDIRECT__N = "/redirect/{n}"


def _register_get__redirect__n(mcp: FastMCP) -> None:
    """Call operation get__redirect_{n} (GET /redirect/{n})."""

    @mcp.tool()
    async def get__redirect__n(n: int) -> dict:
        """302 Redirects n times."""
        url = BASE_URL.rstrip("/") + _PATH_GET__REDIRECT__N
        url = url.replace("{n}", urllib.parse.quote(str(n)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__RELATIVE_REDIRECT__N = "/relative-redirect/{n}"


def _register_get__relative_redirect__n(mcp: FastMCP) -> None:
    """Call operation get__relative-redirect_{n} (GET /relative-redirect/{n})."""

    @mcp.tool()
    async def get__relative_redirect__n(n: int) -> dict:
        """Relatively 302 Redirects n times."""
        url = BASE_URL.rstrip("/") + _PATH_GET__RELATIVE_REDIRECT__N
        url = url.replace("{n}", urllib.parse.quote(str(n)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__RESPONSE_HEADERS = "/response-headers"


def _register_get__response_headers(mcp: FastMCP) -> None:
    """Call operation get__response-headers (GET /response-headers)."""

    @mcp.tool()
    async def get__response_headers(freeform: Optional[str] = None) -> dict:
        """Returns a set of response headers from the query string."""
        url = BASE_URL.rstrip("/") + _PATH_GET__RESPONSE_HEADERS
        params: dict[str, Any] = {}
        if freeform is not None:
            params["freeform"] = freeform
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_POST__RESPONSE_HEADERS = "/response-headers"


def _register_post__response_headers(mcp: FastMCP) -> None:
    """Call operation post__response-headers (POST /response-headers)."""

    @mcp.tool()
    async def post__response_headers(freeform: Optional[str] = None) -> dict:
        """Returns a set of response headers from the query string."""
        url = BASE_URL.rstrip("/") + _PATH_POST__RESPONSE_HEADERS
        params: dict[str, Any] = {}
        if freeform is not None:
            params["freeform"] = freeform
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.post(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__ROBOTS_TXT = "/robots.txt"


def _register_get__robots_txt(mcp: FastMCP) -> None:
    """Call operation get__robots.txt (GET /robots.txt)."""

    @mcp.tool()
    async def get__robots_txt() -> dict:
        """Returns some robots.txt rules."""
        url = BASE_URL.rstrip("/") + _PATH_GET__ROBOTS_TXT
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_DELETE__STATUS__CODES = "/status/{codes}"


def _register_delete__status__codes(mcp: FastMCP) -> None:
    """Call operation delete__status_{codes} (DELETE /status/{codes})."""

    @mcp.tool()
    async def delete__status__codes(codes: str) -> dict:
        """Return status code or random status code if more than one are given"""
        url = BASE_URL.rstrip("/") + _PATH_DELETE__STATUS__CODES
        url = url.replace("{codes}", urllib.parse.quote(str(codes)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.delete(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__STATUS__CODES = "/status/{codes}"


def _register_get__status__codes(mcp: FastMCP) -> None:
    """Call operation get__status_{codes} (GET /status/{codes})."""

    @mcp.tool()
    async def get__status__codes(codes: str) -> dict:
        """Return status code or random status code if more than one are given"""
        url = BASE_URL.rstrip("/") + _PATH_GET__STATUS__CODES
        url = url.replace("{codes}", urllib.parse.quote(str(codes)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_PATCH__STATUS__CODES = "/status/{codes}"


def _register_patch__status__codes(mcp: FastMCP) -> None:
    """Call operation patch__status_{codes} (PATCH /status/{codes})."""

    @mcp.tool()
    async def patch__status__codes(codes: str) -> dict:
        """Return status code or random status code if more than one are given"""
        url = BASE_URL.rstrip("/") + _PATH_PATCH__STATUS__CODES
        url = url.replace("{codes}", urllib.parse.quote(str(codes)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.patch(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_POST__STATUS__CODES = "/status/{codes}"


def _register_post__status__codes(mcp: FastMCP) -> None:
    """Call operation post__status_{codes} (POST /status/{codes})."""

    @mcp.tool()
    async def post__status__codes(codes: str) -> dict:
        """Return status code or random status code if more than one are given"""
        url = BASE_URL.rstrip("/") + _PATH_POST__STATUS__CODES
        url = url.replace("{codes}", urllib.parse.quote(str(codes)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.post(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_PUT__STATUS__CODES = "/status/{codes}"


def _register_put__status__codes(mcp: FastMCP) -> None:
    """Call operation put__status_{codes} (PUT /status/{codes})."""

    @mcp.tool()
    async def put__status__codes(codes: str) -> dict:
        """Return status code or random status code if more than one are given"""
        url = BASE_URL.rstrip("/") + _PATH_PUT__STATUS__CODES
        url = url.replace("{codes}", urllib.parse.quote(str(codes)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.put(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__STREAM_BYTES__N = "/stream-bytes/{n}"


def _register_get__stream_bytes__n(mcp: FastMCP) -> None:
    """Call operation get__stream-bytes_{n} (GET /stream-bytes/{n})."""

    @mcp.tool()
    async def get__stream_bytes__n(n: int) -> dict:
        """Streams n random bytes generated with given seed, at given chunk size per packet."""
        url = BASE_URL.rstrip("/") + _PATH_GET__STREAM_BYTES__N
        url = url.replace("{n}", urllib.parse.quote(str(n)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__STREAM__N = "/stream/{n}"


def _register_get__stream__n(mcp: FastMCP) -> None:
    """Call operation get__stream_{n} (GET /stream/{n})."""

    @mcp.tool()
    async def get__stream__n(n: int) -> dict:
        """Stream n JSON responses"""
        url = BASE_URL.rstrip("/") + _PATH_GET__STREAM__N
        url = url.replace("{n}", urllib.parse.quote(str(n)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__USER_AGENT = "/user-agent"


def _register_get__user_agent(mcp: FastMCP) -> None:
    """Call operation get__user-agent (GET /user-agent)."""

    @mcp.tool()
    async def get__user_agent() -> dict:
        """Return the incoming requests's User-Agent header."""
        url = BASE_URL.rstrip("/") + _PATH_GET__USER_AGENT
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__UUID = "/uuid"


def _register_get__uuid(mcp: FastMCP) -> None:
    """Call operation get__uuid (GET /uuid)."""

    @mcp.tool()
    async def get__uuid() -> dict:
        """Return a UUID4."""
        url = BASE_URL.rstrip("/") + _PATH_GET__UUID
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GET__XML = "/xml"


def _register_get__xml(mcp: FastMCP) -> None:
    """Call operation get__xml (GET /xml)."""

    @mcp.tool()
    async def get__xml() -> dict:
        """Returns a simple XML document."""
        url = BASE_URL.rstrip("/") + _PATH_GET__XML
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}

_register_get__absolute_redirect__n(mcp)
_register_delete__anything(mcp)
_register_get__anything(mcp)
_register_patch__anything(mcp)
_register_post__anything(mcp)
_register_put__anything(mcp)
_register_delete__anything__anything(mcp)
_register_get__anything__anything(mcp)
_register_patch__anything__anything(mcp)
_register_post__anything__anything(mcp)
_register_put__anything__anything(mcp)
_register_get__base64__value(mcp)
_register_get__basic_auth__user___passwd(mcp)
_register_get__bearer(mcp)
_register_get__brotli(mcp)
_register_get__bytes__n(mcp)
_register_get__cache(mcp)
_register_get__cache__value(mcp)
_register_get__cookies(mcp)
_register_get__cookies_delete(mcp)
_register_get__cookies_set(mcp)
_register_get__cookies_set__name___value(mcp)
_register_get__deflate(mcp)
_register_delete__delay__delay(mcp)
_register_get__delay__delay(mcp)
_register_patch__delay__delay(mcp)
_register_post__delay__delay(mcp)
_register_put__delay__delay(mcp)
_register_delete__delete(mcp)
_register_get__deny(mcp)
_register_get__digest_auth__qop___user___passwd(mcp)
_register_get__digest_auth__qop___user___passwd___algorithm(mcp)
_register_get__digest_auth__qop___user___passwd___algorithm___stale_after(mcp)
_register_get__drip(mcp)
_register_get__encoding_utf8(mcp)
_register_get__etag__etag(mcp)
_register_get__get(mcp)
_register_get__gzip(mcp)
_register_get__headers(mcp)
_register_get__hidden_basic_auth__user___passwd(mcp)
_register_get__html(mcp)
_register_get__image(mcp)
_register_get__image_jpeg(mcp)
_register_get__image_png(mcp)
_register_get__image_svg(mcp)
_register_get__image_webp(mcp)
_register_get__ip(mcp)
_register_get__json(mcp)
_register_get__links__n___offset(mcp)
_register_patch__patch(mcp)
_register_post__post(mcp)
_register_put__put(mcp)
_register_get__range__numbytes(mcp)
_register_delete__redirect_to(mcp)
_register_get__redirect_to(mcp)
_register_patch__redirect_to(mcp)
_register_post__redirect_to(mcp)
_register_put__redirect_to(mcp)
_register_get__redirect__n(mcp)
_register_get__relative_redirect__n(mcp)
_register_get__response_headers(mcp)
_register_post__response_headers(mcp)
_register_get__robots_txt(mcp)
_register_delete__status__codes(mcp)
_register_get__status__codes(mcp)
_register_patch__status__codes(mcp)
_register_post__status__codes(mcp)
_register_put__status__codes(mcp)
_register_get__stream_bytes__n(mcp)
_register_get__stream__n(mcp)
_register_get__user_agent(mcp)
_register_get__uuid(mcp)
_register_get__xml(mcp)

if __name__ == "__main__":
    mcp.run()
