import { createHash, randomUUID } from 'node:crypto';
import { constants, lstat, mkdir, open, readFile, realpath, rename, stat, unlink } from 'node:fs/promises';
import { basename, isAbsolute, resolve } from 'node:path';
import { CorrelationSafetyError, CorrelationStore, createIntent, isCredentialShaped, requestFingerprint, transition, type CorrelationRecord } from './correlation-store.js';
import { OaeClient, OaeHttpError, safeOaeBaseUrl, TERMINAL_STATES, type OaeTask, type TaskMessage, type TaskState } from './openagentemail.js';

/** Fixture authority may read only its documented OAE-scoped token names. */
const TOKEN_PATTERN = /^OAE_[A-Z0-9_]{1,120}_TOKEN$/;
const SAFE = /^[A-Za-z0-9 ._:@/\-\[\]]{1,240}$/;
const UUID = /^(?!00000000-0000-0000-0000-000000000000$)[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const MAX_SCENARIO_BYTES = 1024 * 1024;

export interface ParticipantScenario { address: string; tokenEnv: string; }
export interface TaskSeed { id: string; from: string; to: string; subject: string; body: string; rootMessageId: string; }
export interface ScenarioStep { action: 'input-required' | 'working' | 'completed' | 'wait'; actor?: string; task: string; body?: string; result?: { decision: 'approved' | 'rejected' }; expectState?: TaskState; }
export interface Scenario { name: string; correlationId: string; participants: Record<string, ParticipantScenario>; tasks: TaskSeed[]; steps: ScenarioStep[]; transitionDelayMs?: number; timeoutMs?: number; }
export interface ScenarioHandlers { pause(input: { scenario: Scenario; task: OaeTask; correlation: CorrelationRecord }): Promise<void>; resume(input: { scenario: Scenario; task: OaeTask; correlation: CorrelationRecord }): Promise<void>; }
export interface Timing { now(): number; sleep(milliseconds: number): Promise<void>; }
/** Test-only descriptor seam; production callers use the unchanged default. */
export interface ScenarioLoadHooks { afterOpen?(): Promise<void>; }
export interface ScenarioRunInput { scenario: Scenario; environment: NodeJS.ProcessEnv; stateDirectory: string; handlers?: Partial<ScenarioHandlers>; timing?: Timing; }
export interface ScenarioResult { scenario: string; correlationId: string; taskId: string; state: TaskState; result?: { decision: 'approved' | 'rejected' }; frameworkPauses: number; frameworkResumes: number; events: Array<{ id: string; from: string; state: TaskState }>; }
export interface FailureExport { scenario: string; step: number; code: 'authority' | 'schema' | 'timeout' | 'conflict'; expectedState?: TaskState; observedState?: TaskState; taskId?: string; correlationId?: string; elapsedMs?: number; }
export interface ArtifactStoreHooks { beforeRename?(): Promise<void>; beforeDirectorySync?(): Promise<void>; }

export class ScenarioFailure extends Error {
  constructor(readonly failure: FailureExport) { super(`scenario ${failure.scenario} failed: ${failure.code}`); }
}

/** Strict caller-supplied YAML boundary. It never accepts credentials or identity provisioning directives. */
export async function loadScenario(path: string, hooks: ScenarioLoadHooks = {}): Promise<Scenario> {
  try {
    if (!path || path.includes('\0') || !/\.ya?ml$/i.test(path)) throw schema('unknown');
    const handle = await open(path, constants.O_RDONLY | constants.O_NOFOLLOW);
    try { await hooks.afterOpen?.(); const entry = await handle.stat(); if (!entry.isFile() || entry.uid !== owner() || entry.size > MAX_SCENARIO_BYTES) throw schema('unknown'); const source = await handle.readFile({ encoding: 'utf8' }); return validateScenario(parseRestrictedYaml(source)); }
    finally { await handle.close(); }
  } catch (error) { if (error instanceof ScenarioFailure) throw error; throw schema('unknown'); }
}

export function validateScenario(value: unknown): Scenario {
  if (!object(value)) throw schema('unknown'); exact(value, ['name', 'correlationId', 'participants', 'tasks', 'steps', 'transitionDelayMs', 'timeoutMs'], ['name', 'correlationId', 'participants', 'tasks', 'steps']);
  const scenario = value as Record<string, unknown>; const name = scenarioName(scenario.name); const correlationId = safe(scenario.correlationId, name); if (!UUID.test(correlationId)) throw schema(name);
  if (!object(scenario.participants) || Array.isArray(scenario.tasks) === false || Array.isArray(scenario.steps) === false) throw schema(name);
  const participants: Record<string, ParticipantScenario> = {}; const addresses = new Set<string>();
  for (const [alias, raw] of Object.entries(scenario.participants)) { if (!/^[a-z][a-z0-9-]{1,63}$/.test(alias) || !object(raw)) throw schema(name); exact(raw, ['address', 'tokenEnv'], ['address', 'tokenEnv']); const address = safe(raw.address, name); const tokenEnv = typeof raw.tokenEnv === 'string' ? raw.tokenEnv : ''; if (address !== address.toLowerCase() || !/^[^@\s]+@[^@\s]+$/.test(address) || !TOKEN_PATTERN.test(tokenEnv) || addresses.has(address)) throw schema(name); addresses.add(address); participants[alias] = { address, tokenEnv }; }
  if (Object.keys(participants).length < 2) throw schema(name);
  const tasks = (scenario.tasks as unknown[]).map((raw) => validateTask(raw, name, correlationId, participants)); const ids = new Set<string>(); for (const task of tasks) { if (ids.has(task.id)) throw schema(name); ids.add(task.id); }
  if (!tasks.length) throw schema(name);
  const steps = (scenario.steps as unknown[]).map((raw) => validateStep(raw, name, participants, ids)); if (!steps.length) throw schema(name);
  const transitionDelayMs = bounded(scenario.transitionDelayMs, name); const timeoutMs = bounded(scenario.timeoutMs, name); if ((transitionDelayMs === undefined) !== (timeoutMs === undefined)) throw schema(name);
  return { name, correlationId, participants, tasks, steps, ...(transitionDelayMs === undefined ? {} : { transitionDelayMs }), ...(timeoutMs === undefined ? {} : { timeoutMs }) };
}

/** Runs only against the local deterministic service; the configurable URL is authority metadata, never a network target here. */
export async function runScenario(input: ScenarioRunInput): Promise<ScenarioResult> {
  const scenario = validateScenario(input.scenario); assertScenarioAuthority(scenario); const actors = resolveActors(scenario, input.environment); const service = new FakeOaeService(scenario, actors); const clients = new Map(Object.keys(actors).map((alias) => [alias, new OaeClient({ baseUrl: actors[alias]!.baseUrl, token: actors[alias]!.token, fetch: service.fetch })]));
  const timing = input.timing ?? realTiming();
  await mkdir(input.stateDirectory, { recursive: true, mode: 0o700 }); const store = new CorrelationStore(resolve(input.stateDirectory, 'correlation'));
  const requester = participantAlias(scenario, 'requester'); const responder = participantAlias(scenario, 'responder'); const first = scenario.tasks[0]!; let record = createIntent({ framework: 'scenario', correlationId: scenario.correlationId, operationKey: `scenario/${scenario.name}`, requestFingerprint: requestFingerprint({ scenario: scenario.name, task: first.id, requester: actors[requester]!.address, responder: actors[responder]!.address }), expectedParticipants: { requester: actors[requester]!.address, responder: actors[responder]!.address }, frameworkStateRef: 'local-fake-oae', approvalItemKey: `scenario-task:${first.id}`, now: '2026-02-04T00:00:00.000Z' }); await store.save(record);
  let pauses = 0; let resumes = 0; let active = service.task(first.id); const activeById = new Map(scenario.tasks.map((task) => [task.id, service.task(task.id)])); let terminal: OaeTask | undefined; let stepIndex = 0;
  try {
    for (const [index, step] of scenario.steps.entries()) {
      stepIndex = index; active = activeById.get(step.task)!;
      const client = step.actor ? clients.get(step.actor) : undefined; if (step.action !== 'wait' && !client) throw new ScenarioFailure({ scenario: scenario.name, step: index, code: 'schema', correlationId: scenario.correlationId });
      if (step.action === 'input-required') { if (active.state === 'input-required') { assertStepActorAuthority(step, active, actors, index, scenario); if (active.messages.at(-1)?.body !== step.body) throw new ScenarioFailure({ scenario: scenario.name, step: index, code: 'conflict', taskId: active.id, correlationId: scenario.correlationId }); } else active = await client!.inputRequired(active.id, step.body!); if (active.id === first.id && record.phase === 'intent-created') { const attemptedAt = new Date(Date.parse(record.updatedAt) + 1).toISOString(); record = transition(record, 'create-attempted', { createAttemptedAt: attemptedAt }, attemptedAt); await store.save(record); record = transition(record, 'task-adopted', { taskId: active.id }); await store.save(record); record = transition(record, 'input-request-attempted', { inputEvidence: digest(step.body!) }); await store.save(record); record = transition(record, 'awaiting-input'); await store.save(record); pauses += 1; await input.handlers?.pause?.({ scenario, task: active, correlation: record }); } }
      else if (step.action === 'working') active = await client!.working(active.id);
      else if (step.action === 'completed') { if (active.state === 'completed') { assertStepActorAuthority(step, active, actors, index, scenario); if (JSON.stringify(active.result) !== JSON.stringify(step.result)) throw new ScenarioFailure({ scenario: scenario.name, step: index, code: 'conflict', taskId: active.id, correlationId: scenario.correlationId }); } else active = await client!.complete(active.id, step.result!); if (active.id === first.id) { terminal = active; if (record.phase === 'awaiting-input') { const message = active.messages.at(-1)!; record = transition(record, 'decision-received', { decisionEvidence: { decision: step.result!.decision, messageId: message.id, evidenceFingerprint: digest(JSON.stringify(step.result)) } }); await store.save(record); record = transition(record, 'resume-started'); await store.save(record); resumes += 1; await input.handlers?.resume?.({ scenario, task: active, correlation: record }); record = transition(record, 'resumed', { resumeEvidence: `scenario:${digest(`${scenario.correlationId}:${active.id}:${message.id}`)}` }); await store.save(record); } } }
      else { const deadline = scenario.timeoutMs; const delay = scenario.transitionDelayMs; if (active.id !== first.id || deadline === undefined || delay === undefined || step.expectState !== 'completed') throw new ScenarioFailure({ scenario: scenario.name, step: index, code: 'schema', taskId: active.id, correlationId: scenario.correlationId }); const started = timing.now(); const waitFor = Math.min(delay, deadline); await timing.sleep(waitFor); const finishedAt = timing.now(); const elapsedMs = Math.max(0, Math.round(finishedAt - started)); if (delay > deadline || finishedAt > started + deadline) throw new ScenarioFailure({ scenario: scenario.name, step: index, code: 'timeout', expectedState: 'completed', observedState: active.state, taskId: active.id, correlationId: scenario.correlationId, elapsedMs }); active = await clients.get(responder)!.complete(active.id, { decision: 'approved' }); const waited = await clients.get(requester)!.waitForTerminal(active.id); active = waited.task; if (!TERMINAL_STATES.has(active.state) || active.state !== step.expectState) throw new ScenarioFailure({ scenario: scenario.name, step: index, code: 'timeout', expectedState: step.expectState, observedState: active.state, taskId: active.id, correlationId: scenario.correlationId, elapsedMs }); if (record.phase === 'awaiting-input') { const message = active.messages.at(-1)!; record = transition(record, 'decision-received', { decisionEvidence: { decision: 'approved', messageId: message.id, evidenceFingerprint: digest(JSON.stringify({ decision: 'approved' })) } }); await store.save(record); record = transition(record, 'resume-started'); await store.save(record); resumes += 1; await input.handlers?.resume?.({ scenario, task: active, correlation: record }); record = transition(record, 'resumed', { resumeEvidence: `scenario:${digest(`${scenario.correlationId}:${active.id}:${message.id}`)}` }); await store.save(record); } terminal = active; }
      activeById.set(step.task, active);
    }
  } catch (error) { if (error instanceof ScenarioFailure) throw error; if (error instanceof OaeHttpError) throw new ScenarioFailure({ scenario: scenario.name, step: stepIndex, code: error.status === 409 ? 'conflict' : 'authority', observedState: active.state, taskId: active.id, correlationId: scenario.correlationId }); throw error; }
  if (!terminal || terminal.state !== 'completed' || record.phase !== 'resumed') throw new ScenarioFailure({ scenario: scenario.name, step: scenario.steps.length - 1, code: 'timeout', observedState: active.state, taskId: active.id, correlationId: scenario.correlationId, elapsedMs: 0 });
  return { scenario: scenario.name, correlationId: scenario.correlationId, taskId: terminal.id, state: terminal.state, result: terminal.result as { decision: 'approved' | 'rejected' }, frameworkPauses: pauses, frameworkResumes: resumes, events: terminal.messages.map((message) => ({ id: message.id, from: message.from, state: message.state })) };
}

export function sanitizeFailure(error: unknown): FailureExport { if (!(error instanceof ScenarioFailure)) return { scenario: 'unknown', step: 0, code: 'schema' }; const value = error.failure; const output: FailureExport = { scenario: typeof value.scenario === 'string' && SAFE.test(value.scenario) ? value.scenario : 'unknown', step: Number.isSafeInteger(value.step) && value.step >= 0 && value.step <= 100_000 ? value.step : 0, code: value.code === 'authority' || value.code === 'schema' || value.code === 'timeout' || value.code === 'conflict' ? value.code : 'schema' }; if (state(value.expectedState)) output.expectedState = value.expectedState; if (state(value.observedState)) output.observedState = value.observedState; if (typeof value.taskId === 'string' && SAFE.test(value.taskId) && !isCredentialShaped(value.taskId)) output.taskId = value.taskId; if (typeof value.correlationId === 'string' && UUID.test(value.correlationId)) output.correlationId = value.correlationId; if (typeof value.elapsedMs === 'number' && Number.isFinite(value.elapsedMs) && value.elapsedMs >= 0 && value.elapsedMs <= 1_000) output.elapsedMs = Math.round(value.elapsedMs); return output; }
/** Owner-only same-directory atomic replacement; replacement races and unsafe targets fail closed. */
export async function writeScenarioArtifact(directory: string, name: 'success.json' | 'failure.json', value: ScenarioResult | FailureExport, hooks: ArtifactStoreHooks = {}): Promise<void> { if (name !== 'success.json' && name !== 'failure.json') throw new CorrelationSafetyError('scenario artifact name is not fixed'); const trusted = await trustedArtifactDirectory(directory); const target = containedArtifact(trusted, name); const before = await artifactIdentity(target); const temporary = containedArtifact(trusted, `.${name}.${randomUUID()}.tmp`); let created = false; try { const handle = await open(temporary, constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | constants.O_NOFOLLOW, 0o600); created = true; try { await handle.writeFile(JSON.stringify(value), 'utf8'); await handle.sync(); } finally { await handle.close(); } await safeArtifactFile(temporary); await hooks.beforeRename?.(); const after = await artifactIdentity(target); if (!sameArtifact(before, after)) throw new CorrelationSafetyError('scenario artifact target was replaced during atomic write'); await rename(temporary, target); created = false; await safeArtifactFile(target); await hooks.beforeDirectorySync?.(); await syncArtifactDirectory(trusted); } catch (error) { if (created) await removeOwnedTemporary(temporary); throw error; } }
export function createLocalFakeService(scenario: Scenario, environment: NodeJS.ProcessEnv): FakeOaeService { const checked = validateScenario(scenario); assertScenarioAuthority(checked); return new FakeOaeService(checked, resolveActors(checked, environment)); }

type Actor = { address: string; token: string; baseUrl: string };
type ArtifactIdentity = { device: number; inode: number } | null;
function realTiming(): Timing { return { now: () => performance.now(), sleep: async (milliseconds) => new Promise<void>((done) => setTimeout(done, milliseconds)) }; }
function owner(): number { const value = process.getuid?.(); if (value === undefined) throw new CorrelationSafetyError('scenario artifact owner cannot be determined'); return value; }
async function trustedArtifactDirectory(directory: string): Promise<string> { await mkdir(directory, { recursive: true, mode: 0o700 }); const entry = await lstat(directory); if (!entry.isDirectory() || entry.isSymbolicLink() || entry.uid !== owner() || (entry.mode & 0o777) !== 0o700) throw new CorrelationSafetyError('scenario artifact directory must be an owner-only regular directory'); return realpath(directory); }
function containedArtifact(directory: string, name: string): string { if (!name || basename(name) !== name || isAbsolute(name) || /[\\/%]/i.test(name)) throw new CorrelationSafetyError('scenario artifact filename escapes its store'); const target = resolve(directory, name); if (!target.startsWith(`${directory}/`)) throw new CorrelationSafetyError('scenario artifact target escapes its store'); return target; }
async function artifactIdentity(path: string): Promise<ArtifactIdentity> { try { return await safeArtifactFile(path); } catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null; throw error; } }
async function safeArtifactFile(path: string): Promise<Exclude<ArtifactIdentity, null>> { const entry = await lstat(path); const followed = await stat(path); if (!entry.isFile() || entry.isSymbolicLink() || !followed.isFile() || entry.uid !== owner() || (entry.mode & 0o777) !== 0o600) throw new CorrelationSafetyError('scenario artifact must be an owner-only regular file'); return { device: entry.dev, inode: entry.ino }; }
function sameArtifact(first: ArtifactIdentity, second: ArtifactIdentity): boolean { return first === null ? second === null : second !== null && first.device === second.device && first.inode === second.inode; }
async function removeOwnedTemporary(path: string): Promise<void> { try { const entry = await lstat(path); if (entry.isFile() && !entry.isSymbolicLink() && entry.uid === owner()) await unlink(path); } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; } }
async function syncArtifactDirectory(directory: string): Promise<void> { const handle = await open(directory, constants.O_RDONLY | constants.O_DIRECTORY); try { await handle.sync(); } finally { await handle.close(); } }
function resolveActors(scenario: Scenario, environment: NodeJS.ProcessEnv): Record<string, Actor> { const rawBaseUrl = environment.OPENAGENTEMAIL_API_URL; let baseUrl: string; try { if (!rawBaseUrl) throw new Error('missing'); baseUrl = safeOaeBaseUrl(rawBaseUrl); } catch { throw new ScenarioFailure({ scenario: scenario.name, step: 0, code: 'authority', correlationId: scenario.correlationId }); } const resolved: Record<string, Actor> = {}; const tokenAuthorities = new Set<string>(); for (const [alias, participant] of Object.entries(scenario.participants)) { const token = environment[participant.tokenEnv]; const authority = typeof token === 'string' ? digest(token) : ''; if (!token || !SAFE.test(token) || isCredentialShaped(token) || tokenAuthorities.has(authority)) throw new ScenarioFailure({ scenario: scenario.name, step: 0, code: 'authority', correlationId: scenario.correlationId }); tokenAuthorities.add(authority); resolved[alias] = { address: participant.address, token, baseUrl }; } return resolved; }
function participantAlias(scenario: Scenario, expected: 'requester' | 'responder'): string { const aliases = Object.entries(scenario.participants).filter(([alias]) => alias === expected).map(([alias]) => alias); if (aliases.length !== 1) throw schema(scenario.name); return aliases[0]!; }
function validateTask(value: unknown, scenario: string, _correlationId: string, participants: Record<string, ParticipantScenario>): TaskSeed { if (!object(value)) throw schema(scenario); exact(value, ['id', 'from', 'to', 'subject', 'body', 'rootMessageId'], ['id', 'from', 'to', 'subject', 'body', 'rootMessageId']); const row = value as Record<string, unknown>; const id = safe(row.id, scenario); const from = safe(row.from, scenario); const to = safe(row.to, scenario); const subject = safe(row.subject, scenario); const body = safe(row.body, scenario); const rootMessageId = safe(row.rootMessageId, scenario); if (!participants[from] || !participants[to] || from === to || !/^[-A-Za-z0-9._]{1,120}$/.test(id) || !/^[-A-Za-z0-9._]{1,120}$/.test(rootMessageId)) throw schema(scenario); return { id, from, to, subject, body, rootMessageId }; }
function assertScenarioAuthority(scenario: Scenario): void { for (const task of scenario.tasks) if (task.from !== 'requester' || task.to !== 'responder' || task.subject !== `Approval [scenario:${scenario.correlationId}]`) throw new ScenarioFailure({ scenario: scenario.name, step: 0, code: 'authority', taskId: task.id, correlationId: scenario.correlationId }); }
/** 重复 no-op 抑制前先核 step.actor 对当前任务有权，避免错 actor 被当成幂等成功。 */
function assertStepActorAuthority(step: ScenarioStep, active: OaeTask, actors: Record<string, Actor>, index: number, scenario: Scenario): void {
  if (!step.actor) throw new ScenarioFailure({ scenario: scenario.name, step: index, code: 'authority', taskId: active.id, correlationId: scenario.correlationId });
  const actor = actors[step.actor];
  if (!actor) throw new ScenarioFailure({ scenario: scenario.name, step: index, code: 'authority', taskId: active.id, correlationId: scenario.correlationId });
  const allowed = (step.action === 'input-required' && actor.address === active.from)
    || ((step.action === 'working' || step.action === 'completed') && actor.address === active.to);
  if (!allowed) throw new ScenarioFailure({ scenario: scenario.name, step: index, code: 'authority', observedState: active.state, taskId: active.id, correlationId: scenario.correlationId });
}
function validateStep(value: unknown, scenario: string, participants: Record<string, ParticipantScenario>, ids: Set<string>): ScenarioStep { if (!object(value)) throw schema(scenario); const row = value as Record<string, unknown>; const action = row.action; if (action !== 'input-required' && action !== 'working' && action !== 'completed' && action !== 'wait') throw schema(scenario); const allowed = action === 'input-required' ? ['action', 'actor', 'task', 'body'] : action === 'working' ? ['action', 'actor', 'task'] : action === 'completed' ? ['action', 'actor', 'task', 'result'] : ['action', 'task', 'expectState']; exact(row, allowed, action === 'wait' ? ['action', 'task', 'expectState'] : ['action', 'actor', 'task']); const task = safe(row.task, scenario); if (!ids.has(task)) throw schema(scenario); if (action === 'wait') { if (!state(row.expectState)) throw schema(scenario); return { action, task, expectState: row.expectState }; } const actor = safe(row.actor, scenario); if (!participants[actor]) throw schema(scenario); if (action === 'input-required') return { action, actor, task, body: safe(row.body, scenario) }; if (action === 'working') return { action, actor, task }; if (!object(row.result) || Object.keys(row.result).length !== 1 || (row.result as { decision?: unknown }).decision !== 'approved' && (row.result as { decision?: unknown }).decision !== 'rejected') throw schema(scenario); return { action, actor, task, result: row.result as { decision: 'approved' | 'rejected' } }; }
function bounded(value: unknown, scenario: string): number | undefined { if (value === undefined) return undefined; if (!Number.isInteger(value) || (value as number) < 0 || (value as number) > 1000) throw schema(scenario); return value as number; }
function object(value: unknown): value is Record<string, unknown> { return !!value && typeof value === 'object' && !Array.isArray(value); }
function exact(value: Record<string, unknown>, allowed: string[], required: string[]): void { const keys = Object.keys(value); if (keys.some((key) => !allowed.includes(key)) || required.some((key) => !(key in value))) throw schema(typeof value.name === 'string' ? value.name : 'unknown'); }
function safe(value: unknown, scenario: string): string { if (typeof value !== 'string' || !SAFE.test(value) || isCredentialShaped(value)) throw schema(scenario); return value; }
function scenarioName(value: unknown): string { if (typeof value !== 'string' || !/^[A-Za-z0-9._:/-]{1,231}$/.test(value) || isCredentialShaped(value) || `scenario/${value}`.length > 240) throw schema('unknown'); return value; }
function state(value: unknown): value is TaskState { return value === 'submitted' || value === 'input-required' || value === 'working' || value === 'completed' || value === 'failed'; }
function schema(scenario: string): ScenarioFailure { return new ScenarioFailure({ scenario, step: 0, code: 'schema' }); }
function digest(value: string): string { return createHash('sha256').update(value).digest('hex'); }

/** Local-only in-memory service: it recognizes only participant-scoped tokens and has no identity/bootstrap route. */
export class FakeOaeService {
  private readonly tasks = new Map<string, OaeTask>(); private readonly tokenIndex: Map<string, Actor>; private sequence = 0; private clockSequence = 0;
  readonly fetch: typeof globalThis.fetch = async (input, init) => {
    const request = input instanceof Request ? input : new Request(input, init); const url = new URL(request.url); const actor = this.actor(request.headers.get('authorization'));
    if (!actor) return json({ error: 'scoped authority required' }, 403); const pathname = this.routedPath(actor, url); if (pathname === null) return json({ error: 'configured fake authority required' }, 403); if (pathname === '/v1/identities') return json({ error: 'identity provisioning unavailable' }, 403);
    if (pathname === '/v1/tasks' && request.method === 'GET') return json({ tasks: [...this.tasks.values()].filter((task) => task.from === actor.address || task.to === actor.address) });
    if (pathname === '/v1/tasks' && request.method === 'POST') return json({ error: 'scenario tasks must be declaratively seeded' }, 403);
    const match = /^\/v1\/tasks\/([^/]+)(?:\/state)?$/.exec(pathname); if (!match) return json({ error: 'not found' }, 404); let id: string; try { id = decodeURIComponent(match[1]!); } catch { return json({ error: 'not found' }, 404); } const task = this.tasks.get(id); if (!task || (task.from !== actor.address && task.to !== actor.address)) return json({ error: 'not found' }, 404);
    if (request.method === 'GET') return json(task, 200, url.searchParams.get('wait') === 'true' ? { 'X-OAE-Wait-Timeout-Sec': '1' } : {});
    if (request.method !== 'POST' || !pathname.endsWith('/state')) return json({ error: 'method' }, 405); const payload = await request.json() as { state?: unknown; body?: unknown; result?: unknown }; return this.update(task, actor, payload);
  };
  constructor(private readonly scenario: Scenario, private readonly actors: Record<string, Actor>) { this.tokenIndex = new Map(Object.values(actors).map((actor) => [digest(actor.token), actor])); for (const seed of scenario.tasks) { const from = actors[seed.from]!.address; const to = actors[seed.to]!.address; const root: TaskMessage = { id: seed.rootMessageId, from, to, subject: seed.subject, date: this.time(), state: 'submitted', body: seed.body }; this.tasks.set(seed.id, { id: seed.id, from, to, subject: seed.subject, state: 'submitted', createdAt: root.date, updatedAt: root.date, messages: [root] }); } }
  task(id: string): OaeTask { const task = this.tasks.get(id); if (!task) throw new Error('missing seeded task'); return task; }
  private actor(header: string | null): Actor | null { if (!header?.startsWith('Bearer ')) return null; return this.tokenIndex.get(digest(header.slice('Bearer '.length))) ?? null; }
  /** Route only a token holder's configured origin and whole base-path segment. */
  private routedPath(actor: Actor, request: URL): string | null {
    const base = new URL(actor.baseUrl); if (request.origin !== base.origin) return null;
    const prefix = base.pathname === '/' ? '' : base.pathname.replace(/\/$/, '');
    if (!prefix) return request.pathname;
    if (!request.pathname.startsWith(`${prefix}/`)) return null;
    return request.pathname.slice(prefix.length);
  }
  private update(task: OaeTask, actor: Actor | null, payload: { state?: unknown; body?: unknown; result?: unknown }): Response { if (!actor || !state(payload.state)) return json({ error: 'scoped authority required' }, 403); const next = payload.state;
    const requester = task.from; const responder = task.to; const allowed = (next === 'input-required' && (task.state === 'submitted' || task.state === 'input-required') && actor.address === requester && typeof payload.body === 'string') || (next === 'working' && task.state === 'input-required' && actor.address === responder) || (next === 'completed' && task.state === 'working' && actor.address === responder && object(payload.result) && Object.keys(payload.result).length === 1 && ((payload.result as { decision?: unknown }).decision === 'approved' || (payload.result as { decision?: unknown }).decision === 'rejected'));
    if (!allowed) return json({ error: 'stale, contradictory, or unauthorized update' }, 409); const event: TaskMessage = { id: `event-${++this.sequence}`, from: actor.address, to: actor.address === requester ? responder : requester, subject: task.subject, date: this.time(), state: next, body: typeof payload.body === 'string' ? payload.body : next, ...(next === 'completed' ? { result: payload.result } : {}) }; const updated: OaeTask = { ...task, state: next, updatedAt: event.date, messages: [...task.messages, event], ...(next === 'completed' ? { result: payload.result } : {}) }; this.tasks.set(task.id, updated); return json(updated);
  }
  private time(): string { return new Date(Date.parse('2026-02-04T00:00:00.000Z') + this.clockSequence++).toISOString(); }
}
function json(value: unknown, status = 200, headers: Record<string, string> = {}): Response { return new Response(JSON.stringify(value), { status, headers: { 'content-type': 'application/json', ...headers } }); }

/** A deliberately small YAML boundary: maps, lists, quoted/plain strings, integers and booleans only; aliases/tags/flow syntax are refused. */
export function parseRestrictedYaml(source: string): unknown {
  type Line = { indent: number; text: string }; const lines: Line[] = [];
  for (const raw of source.split(/\r?\n/)) { if (!raw.trim()) continue; if (/\t|[&*!]/.test(raw)) throw schema('unknown'); const match = /^( *)(.*)$/.exec(raw)!; const spacing = match[1] ?? ''; const text = match[2] ?? ''; if (text.startsWith('#')) continue; if (spacing.length % 2 || spacing.length / 2 > 32 || !text) throw schema('unknown'); lines.push({ indent: spacing.length, text }); }
  let cursor = 0; const scalar = (raw: string): unknown => { const value = raw.trim(); if (!value || value.includes(' #')) throw schema('unknown'); if (value.startsWith('"') && value.endsWith('"')) { try { return JSON.parse(value); } catch { throw schema('unknown'); } } if (/^-?\d+$/.test(value)) return Number(value); if (value === 'true') return true; if (value === 'false') return false; if (value === 'null') return null; if (/[:#]/.test(value)) throw schema('unknown'); return value; };
  const pair = (text: string): [string, string] => { const match = /^([A-Za-z][A-Za-z0-9-]*):(?:[ ](.*)|)$/.exec(text); if (!match) throw schema('unknown'); return [match[1]!, match[2] ?? '']; };
  const map = (indent: number): Record<string, unknown> => { const result: Record<string, unknown> = {}; while (cursor < lines.length && lines[cursor]!.indent === indent && !lines[cursor]!.text.startsWith('- ')) { const [key, raw] = pair(lines[cursor]!.text); if (key in result) throw schema('unknown'); cursor += 1; result[key] = raw ? scalar(raw) : child(indent); } return result; };
  const child = (parent: number): unknown => { if (cursor >= lines.length || lines[cursor]!.indent !== parent + 2) throw schema('unknown'); return lines[cursor]!.text.startsWith('- ') ? list(lines[cursor]!.indent) : map(lines[cursor]!.indent); };
  const list = (indent: number): unknown[] => { const result: unknown[] = []; while (cursor < lines.length && lines[cursor]!.indent === indent && lines[cursor]!.text.startsWith('- ')) { const rest = lines[cursor]!.text.slice(2); const [key, raw] = pair(rest); const item: Record<string, unknown> = {}; cursor += 1; item[key] = raw ? scalar(raw) : child(indent); if (cursor < lines.length && lines[cursor]!.indent > indent) { if (lines[cursor]!.indent !== indent + 2) throw schema('unknown'); const extra = map(lines[cursor]!.indent); for (const [extraKey, value] of Object.entries(extra)) { if (extraKey in item) throw schema('unknown'); item[extraKey] = value; } } result.push(item); } return result; };
  const root = map(0); if (cursor !== lines.length) throw schema('unknown'); return root;
}
