import type { AuthContext, Scope } from "./auth";
import type { MissionRow } from "./db";
import { AppError } from "./errors";
import { createMissionOperation, missionView } from "./mission";
import type { CreateMissionInput } from "./schemas";

export const DEMO_KEY_ID = "key_public_demo";
export const DEMO_WARMUP_CRON = "0 * * * *";

const HOUR_MS = 3_600_000;
const PLATFORM_ROTATION = ["linkedin", "x", "reddit", "xiaohongshu", "wechat"] as const;

type DemoMissionInput = Pick<CreateMissionInput, "sourceUrl" | "objective" | "platform" | "locale">;

function demoAuth(): AuthContext {
  const scopes = new Set<Scope>(["mission:create", "mission:read"]);
  return { apiKeyId: DEMO_KEY_ID, label: "public-demo", scopes };
}

function hourStart(date: Date): string {
  return new Date(Math.floor(date.getTime() / HOUR_MS) * HOUR_MS).toISOString();
}

function platformForBucket(bucketIso: string): (typeof PLATFORM_ROTATION)[number] {
  const index = Math.floor(Date.parse(bucketIso) / HOUR_MS) % PLATFORM_ROTATION.length;
  return PLATFORM_ROTATION[index] ?? "linkedin";
}

function demoInput(env: Env, bucketIso: string): DemoMissionInput {
  return {
    sourceUrl: env.DEMO_SOURCE_URL ?? "https://www.finfold.app/",
    objective: "leads",
    platform: platformForBucket(bucketIso),
    locale: "en",
  };
}

async function latestDemoRow(db: D1Database): Promise<MissionRow | null> {
  return db
    .prepare("SELECT * FROM missions WHERE api_key_id = ? ORDER BY created_at DESC LIMIT 1")
    .bind(DEMO_KEY_ID)
    .first<MissionRow>();
}

async function generateForBucket(env: Env, bucketIso: string, requestId: string): Promise<void> {
  const input = demoInput(env, bucketIso);
  await createMissionOperation(env, demoAuth(), input, `demo-${bucketIso}`, requestId);
}

export type DemoView = { status: number; body: Record<string, unknown>; cacheControl: string };

function demoMeta(env: Env, row: MissionRow, bucketIso: string, fresh: boolean, fallback?: string, lastErrorCode?: string) {
  return {
    mode: "public-readonly-demo",
    sourceUrl: env.DEMO_SOURCE_URL ?? "https://www.finfold.app/",
    refreshCadence: "hourly",
    platformRotation: [...PLATFORM_ROTATION],
    generatedForHour: hourStart(new Date(row.created_at)),
    nextRefreshAt: new Date(Date.parse(bucketIso) + HOUR_MS).toISOString(),
    fresh,
    ...(fallback ? { fallback } : {}),
    ...(lastErrorCode ? { lastErrorCode } : {}),
    note:
      "Generated by the exact production pipeline under an isolated demo key. Reviewers holding a review key can create missions for any public business URL via POST /v1/missions.",
  };
}

/**
 * Returns the current public demo mission, generating one for the current UTC
 * hour on demand when the hourly warm-up has not run yet. Falls back to the
 * last good demo mission when a fresh generation is in flight or fails; throws
 * the typed generation error only when no fallback exists.
 */
export async function demoMissionView(env: Env, requestId: string, now: Date = new Date()): Promise<DemoView> {
  const bucketIso = hourStart(now);
  const row = await latestDemoRow(env.DB);
  if (row && row.created_at >= bucketIso) {
    return {
      status: 200,
      body: { demo: demoMeta(env, row, bucketIso, true), ...(await missionView(env.DB, row)) },
      cacheControl: "public, max-age=60",
    };
  }

  try {
    await generateForBucket(env, bucketIso, requestId);
  } catch (error) {
    if (row) {
      const concurrent = error instanceof AppError && error.code === "REQUEST_IN_PROGRESS";
      return {
        status: 200,
        body: {
          demo: demoMeta(
            env,
            row,
            bucketIso,
            false,
            concurrent ? "concurrent-warmup" : "last-good",
            error instanceof AppError ? error.code : "INTERNAL_ERROR",
          ),
          ...(await missionView(env.DB, row)),
        },
        cacheControl: "no-store",
      };
    }
    if (error instanceof AppError && error.code === "REQUEST_IN_PROGRESS") {
      throw new AppError("DEMO_UNAVAILABLE", "The demo mission is being refreshed; retry within a minute.", 503, {
        retryable: true,
      });
    }
    throw error;
  }

  const fresh = await latestDemoRow(env.DB);
  if (!fresh) throw new AppError("DEMO_UNAVAILABLE", "The demo mission could not be loaded.", 503, { retryable: true });
  return {
    status: 200,
    body: { demo: demoMeta(env, fresh, bucketIso, true), ...(await missionView(env.DB, fresh)) },
    cacheControl: "public, max-age=60",
  };
}

/** Hourly cron warm-up so the public route never blocks on generation. */
export async function warmDemoMission(env: Env): Promise<void> {
  try {
    const bucketIso = hourStart(new Date());
    const existing = await latestDemoRow(env.DB);
    if (existing && existing.created_at >= bucketIso) return;
    await generateForBucket(env, bucketIso, `cron-demo-${bucketIso}`);
    console.log(JSON.stringify({ event: "demo_warmup", bucket: bucketIso, status: "generated" }));
  } catch (error) {
    const code = error instanceof AppError ? error.code : "INTERNAL_ERROR";
    console.log(JSON.stringify({ event: "demo_warmup", status: "skipped", code }));
  }
}
