import assert from 'node:assert/strict';
import test from 'node:test';
import { chmod, lstat, mkdir, mkdtemp, readFile, readdir, rename, symlink, unlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { OaeClient } from '../src/openagentemail.js';
import { createLocalFakeService, loadScenario, parseRestrictedYaml, runScenario, sanitizeFailure, ScenarioFailure, writeScenarioArtifact } from '../src/scenario-runner.js';

const scenarios = join(process.cwd(), 'scenarios');
const environment = { OPENAGENTEMAIL_API_URL: 'http://127.0.0.1', OAE_FIXTURE_REQUESTER_TOKEN: 'fixture-requester-scope', OAE_FIXTURE_RESPONDER_TOKEN: 'fixture-responder-scope' };
async function stateDirectory(label: string): Promise<string> { return mkdtemp(join(tmpdir(), `r4-${label}-`)); }
async function scenario(name: string) { return loadScenario(join(scenarios, `${name}.yaml`)); }

test('R4 caller-supplied YAML runs the complete submitted/input/working/completed path with scoped authors and exactly once handlers', async () => {
  const state = await stateDirectory('complete'); const input = await scenario('input-resume'); let pauses = 0; let resumes = 0;
  const result = await runScenario({ scenario: input, environment, stateDirectory: state, handlers: { pause: async () => { pauses += 1; }, resume: async () => { resumes += 1; } } });
  assert.deepEqual(result, { scenario: 'input-resume', correlationId: '11111111-1111-4111-8111-111111111111', taskId: 'scenario-task-1', state: 'completed', result: { decision: 'approved' }, frameworkPauses: 1, frameworkResumes: 1, events: [{ id: 'root-1', from: 'requester@example.test', state: 'submitted' }, { id: 'event-1', from: 'requester@example.test', state: 'input-required' }, { id: 'event-2', from: 'responder@example.test', state: 'working' }, { id: 'event-3', from: 'responder@example.test', state: 'completed' }] }); assert.equal(pauses, 1); assert.equal(resumes, 1);
  const record = JSON.parse(await readFile(join(state, 'correlation', '11111111-1111-4111-8111-111111111111.json'), 'utf8')) as Record<string, unknown>; assert.equal(record.phase, 'resumed'); assert.equal(record.taskId, 'scenario-task-1'); assert.equal((await lstat(join(state, 'correlation', '11111111-1111-4111-8111-111111111111.json'))).mode & 0o777, 0o600);
});

test('R4 restricted YAML parser accepts caller paths and all seven checked-in scenarios deterministically', async () => {
  const directory = await stateDirectory('caller'); const copied = join(directory, 'caller-supplied.yaml'); const source = await readFile(join(scenarios, 'input-resume.yaml'), 'utf8'); await writeFile(copied, source, { mode: 0o600 }); const input = await loadScenario(copied); assert.equal(input.name, 'input-resume');
  for (const name of ['input-resume', 'duplicate-delivery', 'timeout', 'stale-update', 'wrong-responder', 'swapped-participants', 'copied-marker']) assert.equal((await scenario(name)).name, name);
  const semanticDirectory = await stateDirectory('semantic'); for (const name of ['copied-marker', 'swapped-participants']) { const adverse = await scenario(name); await assert.rejects(() => runScenario({ scenario: adverse, environment, stateDirectory: semanticDirectory }), ScenarioFailure); await assert.rejects(() => lstat(join(semanticDirectory, 'correlation'))); }
});

test('R4 restricted YAML parser rejects syntax/schema/path confusion before token resolution or service mutation', async () => {
  const directory = await stateDirectory('parser'); const source = await readFile(join(scenarios, 'input-resume.yaml'), 'utf8'); const invalid: Record<string, string> = {
    anchor: `&anchor\n${source}`, alias: `${source}\nname: *anchor\n`, tag: `${source}\nname: !!str input-resume\n`, flow: source.replace('participants:', 'participants: {}\n#'), directive: `---\n${source}`, multidoc: `${source}\n---\n${source}`, duplicateKey: `${source}\nname: duplicate\n`, oddIndent: source.replace('  requester:', '   requester:'), inconsistentIndent: source.replace('      decision: approved', '        decision: approved'), scalarConfusion: source.replace('name: input-resume', 'name: true'), commentEdge: source.replace('name: input-resume', 'name: input-resume # comment'), colonEdge: source.replace('body: safe-workflow-r4', 'body: raw:colon'), unknown: `${source}\nunknown: no\n`, missing: source.replace('rootMessageId: root-1\n', ''), duplicateIdentity: source.replace('responder@example.test', 'requester@example.test'), duplicateSeed: source.replace('tasks:\n', 'tasks:\n  - id: scenario-task-1\n    from: requester\n    to: responder\n    subject: "Approval [scenario:11111111-1111-4111-8111-111111111111]"\n    body: safe-workflow-r4\n    rootMessageId: duplicate-root\n'), unsafe: source.replace('body: safe-workflow-r4', 'body: Bearer canary'),
  };
  for (const [name, content] of Object.entries(invalid)) { const path = join(directory, `${name}.yaml`); await writeFile(path, content, { mode: 0o600 }); await assert.rejects(() => loadScenario(path), ScenarioFailure, name); }
  const link = join(directory, 'linked.yaml'); await writeFile(copiedPath(directory), source, { mode: 0o600 }); await symlink(copiedPath(directory), link); await assert.rejects(() => loadScenario(link), ScenarioFailure); const nonregular = join(directory, 'directory.yaml'); await mkdir(nonregular, { mode: 0o700 }); await assert.rejects(() => loadScenario(nonregular), ScenarioFailure); const oversized = join(directory, 'oversized.yaml'); await writeFile(oversized, 'x'.repeat(1024 * 1024 + 1), { mode: 0o600 }); await assert.rejects(() => loadScenario(oversized), ScenarioFailure); await assert.rejects(() => loadScenario(join(directory, 'not-yaml.txt')), ScenarioFailure); const missing: NodeJS.ProcessEnv = { ...environment }; missing.OAE_FIXTURE_RESPONDER_TOKEN = undefined; const valid = await scenario('input-resume'); await assert.rejects(() => runScenario({ scenario: valid, environment: missing, stateDirectory: join(directory, 'no-token-mutation') }), ScenarioFailure); await assert.rejects(() => lstat(join(directory, 'no-token-mutation', 'correlation')));
});

test('R5d pathname replacement after open cannot alter descriptor-bound YAML parsing, token resolution, or service work', async () => {
  const directory = await stateDirectory('descriptor-replacement'); const source = await readFile(join(scenarios, 'input-resume.yaml'), 'utf8'); const path = join(directory, 'caller.yaml'); const replacement = join(directory, 'replacement.yaml'); await writeFile(path, source, { mode: 0o600 }); await writeFile(replacement, source.replace('input-resume', 'replacement-canary').replace('OAE_FIXTURE_REQUESTER_TOKEN', 'ATTACKER_TOKEN'), { mode: 0o600 }); let hookCalls = 0;
  const parsed = await loadScenario(path, { afterOpen: async () => { hookCalls += 1; await rename(replacement, path); } }); assert.equal(hookCalls, 1); assert.equal(parsed.name, 'input-resume'); assert.equal(parsed.participants.requester!.tokenEnv, 'OAE_FIXTURE_REQUESTER_TOKEN'); const result = await runScenario({ scenario: parsed, environment, stateDirectory: join(directory, 'state') }); assert.equal(result.state, 'completed');
});

test('R5e restricted YAML nesting is bounded before service work while depth 32 remains structurally parseable', async () => {
  const nested = (depth: number) => Array.from({ length: depth }, (_, index) => `${'  '.repeat(index)}level${index}:`).join('\n') + `\n${'  '.repeat(depth)}leaf: value\n`; assert.ok(parseRestrictedYaml(nested(32))); assert.throws(() => parseRestrictedYaml(nested(33)), ScenarioFailure);
  const directory = await stateDirectory('deep-yaml'); const path = join(directory, 'deep.yaml'); await writeFile(path, nested(33), { mode: 0o600 }); await assert.rejects(() => loadScenario(path), ScenarioFailure); await assert.rejects(() => lstat(join(directory, 'state', 'correlation')));
});

test('R5e fake server follows duplicate transport parity while runner suppresses duplicate effects at its boundary', async () => {
  const input = await scenario('input-resume'); const service = createLocalFakeService(input, environment); const requester = new OaeClient({ baseUrl: environment.OPENAGENTEMAIL_API_URL!, token: environment.OAE_FIXTURE_REQUESTER_TOKEN!, fetch: service.fetch }); const responder = new OaeClient({ baseUrl: environment.OPENAGENTEMAIL_API_URL!, token: environment.OAE_FIXTURE_RESPONDER_TOKEN!, fetch: service.fetch }); await requester.inputRequired('scenario-task-1', 'first'); const repeated = await requester.inputRequired('scenario-task-1', 'first'); assert.equal(repeated.messages.filter((message) => message.state === 'input-required').length, 2); await responder.working('scenario-task-1'); await responder.complete('scenario-task-1', { decision: 'approved' }); await assert.rejects(() => responder.complete('scenario-task-1', { decision: 'approved' }));
  const result = await runScenario({ scenario: await scenario('duplicate-delivery'), environment, stateDirectory: await stateDirectory('duplicate-boundary') }); assert.equal(result.events.filter((event) => event.state === 'input-required').length, 1); assert.equal(result.events.filter((event) => event.state === 'completed').length, 1); assert.equal(result.frameworkResumes, 1);
});

test('R5e sanitizeFailure reconstructs only documented bounded fields', () => {
  const hostile = new ScenarioFailure({ scenario: 'safe', step: 1, code: 'timeout', expectedState: 'completed', observedState: 'working', taskId: 'task-1', correlationId: '11111111-1111-4111-8111-111111111111', elapsedMs: 5, authorization: 'Bearer canary', rawBody: 'body-canary', extra: 'nope' } as never); const sanitized = sanitizeFailure(hostile); assert.deepEqual(sanitized, { scenario: 'safe', step: 1, code: 'timeout', expectedState: 'completed', observedState: 'working', taskId: 'task-1', correlationId: '11111111-1111-4111-8111-111111111111', elapsedMs: 5 }); assert.deepEqual(Object.keys(sanitized).sort(), ['code', 'correlationId', 'elapsedMs', 'expectedState', 'observedState', 'scenario', 'step', 'taskId']);
});

test('R4 fake authority separates requester/responder tokens and exposes no identity provisioning or admin bootstrap', async () => {
  const input = await scenario('input-resume'); const service = createLocalFakeService(input, environment); const identity = await service.fetch('http://127.0.0.1/v1/identities', { method: 'POST', headers: { authorization: `Bearer ${environment.OAE_FIXTURE_REQUESTER_TOKEN}` } }); const unscoped = await service.fetch('http://127.0.0.1/v1/tasks'); assert.equal(identity.status, 403); assert.equal(unscoped.status, 403); const body = await identity.text(); assert.ok(!body.includes(environment.OAE_FIXTURE_REQUESTER_TOKEN!)); assert.ok(!body.includes('admin'));
});

test('R4 ordinary polling observes non-terminal state while wait=true is terminal-only and returns its cap header', async () => {
  const input = await scenario('input-resume'); const service = createLocalFakeService(input, environment); const requester = new OaeClient({ baseUrl: environment.OPENAGENTEMAIL_API_URL!, token: environment.OAE_FIXTURE_REQUESTER_TOKEN!, fetch: service.fetch }); const responder = new OaeClient({ baseUrl: environment.OPENAGENTEMAIL_API_URL!, token: environment.OAE_FIXTURE_RESPONDER_TOKEN!, fetch: service.fetch });
  assert.equal((await requester.get('scenario-task-1')).state, 'submitted'); const waiting = await requester.waitForTerminal('scenario-task-1'); assert.equal(waiting.task.state, 'submitted'); assert.equal(waiting.timeoutSec, 1); await requester.inputRequired('scenario-task-1', 'approve-or-reject'); await responder.working('scenario-task-1'); await responder.complete('scenario-task-1', { decision: 'approved' }); const terminal = await requester.waitForTerminal('scenario-task-1'); assert.equal(terminal.task.state, 'completed'); assert.equal(terminal.timeoutSec, 1);
});

test('R5l local fake service binds every scoped token to its validated origin and base-path prefix', async () => {
  const input = await scenario('input-resume');
  const httpsEnvironment = { ...environment, OPENAGENTEMAIL_API_URL: 'https://oae.example.test/tenant-a' }; const httpsCompleted = await runScenario({ scenario: input, environment: httpsEnvironment, stateDirectory: await stateDirectory('r5l-prefixed-https') }); assert.equal(httpsCompleted.state, 'completed'); const httpsService = createLocalFakeService(input, httpsEnvironment);
  const requester = new OaeClient({ baseUrl: httpsEnvironment.OPENAGENTEMAIL_API_URL, token: httpsEnvironment.OAE_FIXTURE_REQUESTER_TOKEN, fetch: httpsService.fetch });
  assert.equal((await requester.get('scenario-task-1')).id, 'scenario-task-1'); assert.equal((await requester.list()).length, 1);
  for (const baseUrl of ['https://wrong.example.test/tenant-a', 'https://oae.example.test/tenant-a-confused', 'https://oae.example.test/tenant-ae']) {
    const confused = new OaeClient({ baseUrl, token: httpsEnvironment.OAE_FIXTURE_REQUESTER_TOKEN, fetch: httpsService.fetch }); await assert.rejects(() => confused.get('scenario-task-1'));
  }
  const loopbackEnvironment = { ...environment, OPENAGENTEMAIL_API_URL: 'http://127.0.0.1/local-fixture' }; const completed = await runScenario({ scenario: input, environment: loopbackEnvironment, stateDirectory: await stateDirectory('r5l-prefixed-loopback') }); assert.equal(completed.state, 'completed');
});

test('R5c multi-task dispatch retains each task state while correlation mutates only the selected approval task', async () => {
  const input = structuredClone(await scenario('input-resume')); const second = structuredClone(input.tasks[0]!); second.id = 'scenario-task-2'; second.rootMessageId = 'root-2'; input.tasks.push(second);
  input.steps.push({ action: 'input-required', actor: 'requester', task: second.id, body: 'secondary-input' }, { action: 'working', actor: 'responder', task: second.id }, { action: 'completed', actor: 'responder', task: second.id, result: { decision: 'rejected' } });
  let pauses = 0; let resumes = 0; const state = await stateDirectory('multi'); const result = await runScenario({ scenario: input, environment, stateDirectory: state, handlers: { pause: async () => { pauses += 1; }, resume: async () => { resumes += 1; } } });
  assert.equal(result.taskId, 'scenario-task-1'); assert.equal(pauses, 1); assert.equal(resumes, 1); const record = JSON.parse(await readFile(join(state, 'correlation', `${input.correlationId}.json`), 'utf8')) as Record<string, unknown>; assert.equal(record.taskId, 'scenario-task-1');
  const invalid = structuredClone(input); invalid.steps.push({ action: 'wait', task: second.id, expectState: 'completed' }); const invalidState = await stateDirectory('cross-task'); await assert.rejects(() => runScenario({ scenario: invalid, environment, stateDirectory: invalidState }), (error: unknown) => error instanceof ScenarioFailure && error.failure.code === 'schema' && error.failure.taskId === 'scenario-task-2');
});

test('R5c fake service list/get/wait are participant scoped and cannot mutate state for a third actor', async () => {
  const input = structuredClone(await scenario('input-resume')); input.participants.observer = { address: 'observer@example.test', tokenEnv: 'OAE_FIXTURE_OBSERVER_TOKEN' }; const env = { ...environment, OAE_FIXTURE_OBSERVER_TOKEN: 'fixture-observer-scope' }; const service = createLocalFakeService(input, env); const requester = new OaeClient({ baseUrl: env.OPENAGENTEMAIL_API_URL!, token: env.OAE_FIXTURE_REQUESTER_TOKEN!, fetch: service.fetch }); const observer = new OaeClient({ baseUrl: env.OPENAGENTEMAIL_API_URL!, token: env.OAE_FIXTURE_OBSERVER_TOKEN!, fetch: service.fetch });
  assert.equal((await requester.get('scenario-task-1')).id, 'scenario-task-1'); assert.equal((await requester.waitForTerminal('scenario-task-1')).timeoutSec, 1); await assert.rejects(() => observer.get('scenario-task-1')); await assert.rejects(() => observer.waitForTerminal('scenario-task-1')); assert.deepEqual(await observer.list(), []); assert.equal((await requester.get('scenario-task-1')).state, 'submitted');
});

test('R4 duplicate delivery is idempotent; timeout measures a real bounded delay and stale/wrong-responder outcomes never add a second framework resume', async () => {
  const duplicate = await runScenario({ scenario: await scenario('duplicate-delivery'), environment, stateDirectory: await stateDirectory('duplicate') }); assert.equal(duplicate.frameworkPauses, 1); assert.equal(duplicate.frameworkResumes, 1); assert.equal(duplicate.events.length, 4);
  const rows: Array<{ name: string; code: 'timeout' | 'conflict'; pauses: number; resumes: number; }> = [{ name: 'timeout', code: 'timeout', pauses: 1, resumes: 0 }, { name: 'wrong-responder', code: 'conflict', pauses: 0, resumes: 0 }, { name: 'stale-update', code: 'conflict', pauses: 1, resumes: 1 }];
  for (const row of rows) { const input = await scenario(row.name); const state = await stateDirectory(row.name); let pauses = 0; let resumes = 0; await assert.rejects(() => runScenario({ scenario: input, environment, stateDirectory: state, handlers: { pause: async () => { pauses += 1; }, resume: async () => { resumes += 1; } } }), (error: unknown) => { assert.ok(error instanceof ScenarioFailure); assert.equal(error.failure.code, row.code); if (row.code === 'timeout') { assert.equal(error.failure.expectedState, 'completed'); assert.equal(error.failure.observedState, 'working'); assert.ok((error.failure.elapsedMs ?? -1) >= 4); assert.ok((error.failure.elapsedMs ?? Infinity) <= 60); assert.equal(error.failure.taskId, 'scenario-task-3'); assert.equal(error.failure.correlationId, '33333333-3333-4333-8333-333333333333'); } return true; }); assert.equal(pauses, row.pauses, row.name); assert.equal(resumes, row.resumes, row.name); }
});

test('R4a scheduler executes the before-deadline completion and fails after-deadline without a later transition', async () => {
  const before = structuredClone(await scenario('timeout')); before.name = 'before-deadline'; before.correlationId = '88888888-8888-4888-8888-888888888888'; before.tasks[0]!.id = 'scenario-task-before'; before.tasks[0]!.rootMessageId = 'root-before'; before.tasks[0]!.subject = `Approval [scenario:${before.correlationId}]`; for (const step of before.steps) step.task = 'scenario-task-before'; before.transitionDelayMs = 2; before.timeoutMs = 20;
  const result = await runScenario({ scenario: before, environment, stateDirectory: await stateDirectory('before-deadline') }); assert.equal(result.state, 'completed'); assert.equal(result.result?.decision, 'approved');
  let clock = 0; const sleeps: number[] = []; let resumes = 0; const expired = await scenario('timeout'); const expiredState = await stateDirectory('after-deadline'); await assert.rejects(() => runScenario({ scenario: expired, environment, stateDirectory: expiredState, timing: { now: () => clock, sleep: async (milliseconds) => { sleeps.push(milliseconds); clock += milliseconds; } }, handlers: { resume: async () => { resumes += 1; } } }), (error: unknown) => { assert.ok(error instanceof ScenarioFailure); assert.deepEqual(error.failure, { scenario: 'timeout', step: 2, code: 'timeout', expectedState: 'completed', observedState: 'working', taskId: 'scenario-task-3', correlationId: '33333333-3333-4333-8333-333333333333', elapsedMs: 5 }); return true; }); assert.deepEqual(sleeps, [5]); assert.equal(resumes, 0); const record = JSON.parse(await readFile(join(expiredState, 'correlation', '33333333-3333-4333-8333-333333333333.json'), 'utf8')) as Record<string, unknown>; assert.equal(record.phase, 'awaiting-input'); await Promise.resolve(); assert.equal(resumes, 0);
  const overslept = structuredClone(before); overslept.name = 'overslept-deadline'; overslept.correlationId = '99999999-9999-4999-8999-999999999999'; overslept.tasks[0]!.id = 'scenario-task-overslept'; overslept.tasks[0]!.rootMessageId = 'root-overslept'; overslept.tasks[0]!.subject = `Approval [scenario:${overslept.correlationId}]`; for (const step of overslept.steps) step.task = 'scenario-task-overslept'; overslept.transitionDelayMs = 2; overslept.timeoutMs = 5; let oversleptClock = 0; const oversleptState = await stateDirectory('overslept-deadline'); await assert.rejects(() => runScenario({ scenario: overslept, environment, stateDirectory: oversleptState, timing: { now: () => oversleptClock, sleep: async () => { oversleptClock = 5.4; } } }), (error: unknown) => error instanceof ScenarioFailure && error.failure.code === 'timeout' && error.failure.elapsedMs === 5);
});

test('R4 sanitizes actual success/failure artifacts and keeps credentials/raw workflow out of exports', async () => {
  const directory = await stateDirectory('exports'); const success = await runScenario({ scenario: await scenario('input-resume'), environment, stateDirectory: join(directory, 'state') }); await writeScenarioArtifact(directory, 'success.json', success); const failure = sanitizeFailure(new ScenarioFailure({ scenario: 'timeout', step: 2, code: 'timeout', expectedState: 'completed', observedState: 'working', taskId: 'scenario-task-3', correlationId: '33333333-3333-4333-8333-333333333333', elapsedMs: 5 })); await writeScenarioArtifact(directory, 'failure.json', failure);
  for (const artifact of [await readFile(join(directory, 'success.json'), 'utf8'), await readFile(join(directory, 'failure.json'), 'utf8'), await readFile(join(directory, 'state', 'correlation', '11111111-1111-4111-8111-111111111111.json'), 'utf8')]) { assert.ok(!artifact.includes('fixture-requester-scope')); assert.ok(!artifact.includes('fixture-responder-scope')); assert.ok(!artifact.includes('safe-workflow-r4')); assert.ok(!artifact.includes('authorization')); } assert.equal((await lstat(join(directory, 'failure.json'))).mode & 0o777, 0o600);
});

test('R4a artifact store rejects unsafe targets and replacement races without corrupting prior bytes', async () => {
  const directory = await stateDirectory('artifact-store'); const first = { scenario: 'safe', step: 0, code: 'schema' as const }; const replacement = { scenario: 'safe', step: 1, code: 'timeout' as const };
  await writeScenarioArtifact(directory, 'failure.json', first); const target = join(directory, 'failure.json'); assert.equal(await readFile(target, 'utf8'), JSON.stringify(first)); assert.equal((await lstat(target)).mode & 0o777, 0o600); await writeScenarioArtifact(directory, 'failure.json', replacement); assert.equal(await readFile(target, 'utf8'), JSON.stringify(replacement));
  const victim = join(directory, 'victim.json'); await writeFile(victim, 'preserve-me', { mode: 0o600 }); const linked = join(directory, 'success.json'); await symlink(victim, linked); await assert.rejects(() => writeScenarioArtifact(directory, 'success.json', first)); assert.equal(await readFile(victim, 'utf8'), 'preserve-me');
  await chmod(target, 0o644); const unsafeBytes = await readFile(target, 'utf8'); await assert.rejects(() => writeScenarioArtifact(directory, 'failure.json', first)); assert.equal(await readFile(target, 'utf8'), unsafeBytes); await chmod(target, 0o600);
  await assert.rejects(() => writeScenarioArtifact(directory, '../failure.json' as never, first)); await assert.rejects(() => writeScenarioArtifact(directory, 'other.json' as never, first)); await unlink(linked); await mkdir(linked, { mode: 0o700 }); await assert.rejects(() => writeScenarioArtifact(directory, 'success.json', first));
  const race = await stateDirectory('artifact-race'); const raceTarget = join(race, 'failure.json'); await writeScenarioArtifact(race, 'failure.json', first); const attacker = join(race, 'attacker.json'); await writeFile(attacker, 'attacker-bytes', { mode: 0o600 }); await assert.rejects(() => writeScenarioArtifact(race, 'failure.json', replacement, { beforeRename: async () => { await rename(attacker, raceTarget); } })); assert.equal(await readFile(raceTarget, 'utf8'), 'attacker-bytes'); assert.deepEqual((await readdir(race)).filter((name) => name.startsWith('.failure.json.')), []);
});

test('R4 executable isolation guard recursively scans real production outputs and proves the scanner catches nested contamination', async () => {
  const root = resolve(process.cwd(), '../..'); const apiPackage = await readFile(join(root, 'packages/api/package.json'), 'utf8'); const dockerfile = await readFile(join(root, 'packages/api/Dockerfile'), 'utf8'); for (const text of [apiPackage, dockerfile]) { assert.ok(!text.includes('openagentemail-adapters-example')); assert.ok(!text.includes('@langchain/langgraph')); assert.ok(!text.includes('@openai/agents')); }
  for (const path of [join(root, 'packages/api/dist'), join(root, 'packages/api/build')]) await assertAdapterFree(await recursiveOutputFiles(path));
  const proof = await stateDirectory('recursive-output'); const nested = join(proof, 'dist', 'nested', 'asset.js'); await mkdir(resolve(nested, '..'), { recursive: true, mode: 0o700 }); await writeFile(nested, 'clean production output', { mode: 0o600 }); await assertAdapterFree(await recursiveOutputFiles(join(proof, 'dist'))); await writeFile(nested, 'import "@openai/agents"', { mode: 0o600 }); await assert.rejects(async () => assertAdapterFree(await recursiveOutputFiles(join(proof, 'dist'))));
});

test('R5g fixture token namespace, monotonic timestamps, and malformed task paths fail before authority or mutation', async () => {
  const input = structuredClone(await scenario('input-resume')); const directory = await stateDirectory('r5g-fixture');
  for (const tokenEnv of ['PATH', 'GITHUB_TOKEN', 'AWS_SECRET_ACCESS_KEY', 'OAE_TOKEN', 'OAE_bad_TOKEN']) { const hostile = structuredClone(input); hostile.participants.requester!.tokenEnv = tokenEnv; await assert.rejects(() => runScenario({ scenario: hostile, environment: { ...environment, [tokenEnv]: 'fixture-requester-scope' }, stateDirectory: join(directory, tokenEnv.replace(/[^A-Za-z0-9]/g, '_')) }), ScenarioFailure); }
  const many = structuredClone(input); for (let index = 2; index <= 105; index += 1) { many.tasks.push({ ...many.tasks[0]!, id: `task-${index}`, rootMessageId: `root-${index}` }); } const service = createLocalFakeService(many, environment); const dates = many.tasks.map((seed) => service.task(seed.id).createdAt); assert.equal(new Set(dates).size, 105); assert.ok(dates.every((date, index) => index === 0 || date > dates[index - 1]!)); const malformed = await service.fetch('http://127.0.0.1/v1/tasks/%E0%A4%A', { headers: { authorization: `Bearer ${environment.OAE_FIXTURE_REQUESTER_TOKEN}` } }); assert.equal(malformed.status, 404);
});

test('R5j validates persisted scenario keys before any service/state work and accepts the exact 240-byte key boundary', async () => {
  const base = await scenario('input-resume'); const directory = await stateDirectory('scenario-key');
  const accepted = structuredClone(base); accepted.name = 'a'.repeat(231); accepted.correlationId = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; accepted.tasks[0]!.subject = `Approval [scenario:${accepted.correlationId}]`; const result = await runScenario({ scenario: accepted, environment, stateDirectory: join(directory, 'accepted') }); assert.equal(result.state, 'completed'); const record = JSON.parse(await readFile(join(directory, 'accepted', 'correlation', `${accepted.correlationId}.json`), 'utf8')) as { operationKey: string }; assert.equal(record.operationKey.length, 240);
  for (const name of ['contains space', 'at@sign', 'bracket[name]', 'x'.repeat(232)]) { const invalid = structuredClone(base); invalid.name = name; const state = join(directory, name.replace(/[^a-z0-9]/gi, '_')); await assert.rejects(() => runScenario({ scenario: invalid, environment, stateDirectory: state }), ScenarioFailure); await assert.rejects(() => lstat(join(state, 'correlation'))); }
});

test('R5j scenario actor authority reuses safe OAE URL rules before token use or service mutation', async () => {
  const base = await scenario('input-resume'); const directory = await stateDirectory('base-url');
  for (const [index, baseUrl] of ['http://127.0.0.1', 'http://localhost', 'https://oae.example.test'].entries()) { const input = structuredClone(base); input.correlationId = `bbbbbbbb-bbbb-4bbb-8bbb-${String(index + 1).padStart(12, '0')}`; input.tasks[0]!.subject = `Approval [scenario:${input.correlationId}]`; assert.equal((await runScenario({ scenario: input, environment: { ...environment, OPENAGENTEMAIL_API_URL: baseUrl }, stateDirectory: join(directory, `ok-${index}`) })).state, 'completed'); }
  for (const [index, baseUrl] of ['http://remote.example.test', 'https://oae.example.test/?query=1', 'https://user:pass@oae.example.test'].entries()) { const input = structuredClone(base); input.correlationId = `cccccccc-cccc-4ccc-8ccc-${String(index + 1).padStart(12, '0')}`; input.tasks[0]!.subject = `Approval [scenario:${input.correlationId}]`; const state = join(directory, `bad-${index}`); await assert.rejects(() => runScenario({ scenario: input, environment: { ...environment, OPENAGENTEMAIL_API_URL: baseUrl }, stateDirectory: state }), ScenarioFailure); await assert.rejects(() => lstat(join(state, 'correlation'))); }
});

test('R5j scenario artifact does not report success before its replacement name is durably synced', async () => {
  const directory = await stateDirectory('artifact-directory-sync'); const initial = { scenario: 'safe', step: 0, code: 'schema' as const }; const replacement = { scenario: 'safe', step: 1, code: 'timeout' as const }; await writeScenarioArtifact(directory, 'failure.json', initial); const target = join(directory, 'failure.json'); await assert.rejects(() => writeScenarioArtifact(directory, 'failure.json', replacement, { beforeDirectorySync: async () => { throw new Error('directory-sync-interrupted'); } }), /directory-sync-interrupted/); assert.equal(await readFile(target, 'utf8'), JSON.stringify(replacement)); assert.deepEqual((await readdir(directory)).filter((name) => name.startsWith('.failure.json.')), []);
});

function copiedPath(directory: string): string { return join(directory, 'anchor-source.yaml'); }
async function recursiveOutputFiles(directory: string): Promise<string[]> { let root; try { root = await lstat(directory); } catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return []; throw error; } if (!root.isDirectory() || root.isSymbolicLink()) throw new Error(`unsafe production output directory: ${directory}`); const files: string[] = []; for (const entry of await readdir(directory, { withFileTypes: true })) { const path = join(directory, entry.name); const metadata = await lstat(path); if (metadata.isSymbolicLink()) throw new Error(`symlinked production output: ${path}`); if (metadata.isDirectory()) files.push(...await recursiveOutputFiles(path)); else if (metadata.isFile()) files.push(path); else throw new Error(`unsupported production output entry: ${path}`); } return files; }
async function assertAdapterFree(paths: string[]): Promise<void> { for (const path of paths) { const contents = await readFile(path, 'utf8'); assert.ok(!path.includes('openagentemail-adapters-example')); assert.ok(!contents.includes('openagentemail-adapters-example')); assert.ok(!contents.includes('@langchain/langgraph')); assert.ok(!contents.includes('@openai/agents')); } }
