/**
 * Build the committed chart artifact from cassettes.
 *
 *   npm run chart   ──▶ docs/evidence/with-without-gate.svg
 *                       docs/evidence/replay.txt
 *
 * Reads the same fixtures the reviewer replays, so the picture in SUBMISSION.md
 * and the receipts a reviewer can reproduce come from one source of truth.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { NexusClient } from '../nexus/client.js';
import { loadBasePolicy } from '../deps.js';
import { mergePolicy } from '../policy/index.js';
import { replay, isoDate, type ReplayInputs } from './replay.js';
import { renderSvg, renderTable } from './render.js';
import { absent, present, type Coverage, type Equity, type Funding, type Metrics, type OpenInterest, type Trades } from '../types.js';

const OUT_SVG = 'docs/evidence/with-without-gate.svg';
const OUT_TXT = 'docs/evidence/replay.txt';

function write(path: string, body: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body);
  console.log(`wrote ${path} (${body.length} bytes)`);
}

export async function buildChart(fixtureDir = 'fixtures'): Promise<void> {
  const client = new NexusClient({ mode: 'replay', fixtureDir });

  const trades = await client.call<Trades>('get_strategy_trades');
  const equity = await client.call<Equity>('get_strategy_equity');
  const metrics = await client.call<Metrics>('get_strategy_metrics');
  const coverage = await client.call<Coverage>('get_historical_coverage');

  if (!trades.ok || !equity.ok) {
    throw new Error('cannot build chart: trades or equity cassette is unavailable');
  }

  // Point-in-time market data per (symbol, entry date). Anything not recorded
  // stays absent, which fails closed rather than inventing a funding rate.
  const market: ReplayInputs['market'] = new Map();
  for (const t of trades.value.trades) {
    const asOf = isoDate(t.entry_ts_ms);
    const key = `${t.symbol}|${asOf}`;
    if (market.has(key)) continue;
    const [funding, oi] = await Promise.all([
      client.call<Funding>('get_historical_funding', { symbol: t.symbol, as_of: asOf }),
      client.call<OpenInterest>('get_open_interest', { symbol: t.symbol, as_of: asOf }),
    ]);
    market.set(key, { funding, openInterest: oi });
  }

  const startingEquity = equity.value.points[0]?.equity ?? 100_000;
  const policy = mergePolicy(loadBasePolicy(), 'permissive');

  const result = replay({
    trades: trades.value,
    equity: equity.value,
    policy,
    startingEquity,
    market,
    staticData: {
      metrics: metrics.ok ? present(metrics.value) : absent<Metrics>(),
      coverage: coverage.ok ? present(coverage.value) : absent<Coverage>(),
    },
  });

  write(OUT_SVG, renderSvg(result));
  write(
    OUT_TXT,
    [
      'Abstain — with-gate vs without-gate replay',
      `run_id ${trades.value.run_id} · policy permissive · generated by src/chart/build.ts`,
      '',
      renderTable(result),
      '',
      'Every decision above was produced by src/gate/index.ts runGate() — the same',
      'function POST /v1/evaluate calls. This is not a reimplementation.',
    ].join('\n'),
  );

  console.log('\n' + renderTable(result));
}

const invokedDirectly = process.argv[1]?.endsWith('build.js') || process.argv[1]?.endsWith('build.ts');
if (invokedDirectly) {
  buildChart().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}

export { readFileSync };
