"""
generated-mcp-server · generated by MCPForge 2.1.0

source API: https://api.exchangerate-api.com/v4
1 tools total.
Run:
    pip install -r requirements.txt
    fastmcp dev server.py
"""
from __future__ import annotations

import asyncio
import os
import urllib.parse
from typing import Any, Optional

import httpx
from fastmcp import FastMCP

mcp = FastMCP("generated-mcp-server")
BASE_URL = os.getenv("API_BASE_URL", "https://api.exchangerate-api.com/v4")



_PATH_GET__LATEST__BASE_CURRENCY = "/latest/{base_currency}"


def _register_get__latest__base_currency(mcp: FastMCP) -> None:
    """Call operation get__latest_{base_currency} (GET /latest/{base_currency})."""

    @mcp.tool()
    async def get__latest__base_currency(base_currency: str) -> dict:
        """Returns latest exchange rates in parameter-supplied base currency."""
        url = BASE_URL.rstrip("/") + _PATH_GET__LATEST__BASE_CURRENCY
        url = url.replace("{base_currency}", urllib.parse.quote(str(base_currency)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}

_register_get__latest__base_currency(mcp)

if __name__ == "__main__":
    mcp.run()
