"""Packaging behavior: preserve review source and reject unsafe or partial artifacts."""

from pathlib import Path
import json
import subprocess

import pytest

from scripts import package_submission as packaging


@pytest.fixture
def project(tmp_path):
    root = tmp_path / "project"
    (root / "source" / "app").mkdir(parents=True)
    (root / "source" / "app" / "main.py").write_text("print('review source')\n")
    (root / "submission.json").write_text('{"draft": true}\n')
    return root


def test_copy_keeps_complete_source_and_drops_generated_trees(project, tmp_path):
    for directory in packaging.EXCLUDED_DIRS:
        generated = project / "source" / directory
        generated.mkdir()
        (generated / "local.key").write_text("local-only material")
        (generated / "python").symlink_to("missing-python")
    (project / "source" / ".env.example").write_text("COOKIE_SECURE=false\n")
    (project / "source" / "research.sqlite3").write_bytes(b"local data")
    (project / "source" / "run.log").write_text("local log")
    (project / "source" / "app" / "main.pyc").write_bytes(b"generated bytecode")
    (project / "source" / ".DS_Store").write_bytes(b"local metadata")
    target = tmp_path / "review"
    result = packaging.package_submission(target, project=project)
    names = {str(path.relative_to(target)) for path in target.rglob("*") if path.is_file()}
    assert names == {"source/app/main.py", "source/.env.example", "submission.json"}
    assert result["files"] == 3
    assert result["bytes"] == sum(path.stat().st_size for path in target.rglob("*") if path.is_file())
    assert (target / "source/app/main.py").read_bytes() == (project / "source/app/main.py").read_bytes()


@pytest.mark.parametrize("name", ["server.pem", "server.KEY", "client.p12", "client.pfx", ".env", ".env.local", ".dev.vars", ".dev.vars.production"])
def test_secret_file_types_rejected_before_copy(project, tmp_path, name):
    (project / name).write_text("inert test material")
    target = tmp_path / "review"
    with pytest.raises(packaging.PackageError, match="secret-bearing file type"):
        packaging.package_submission(target, project=project)
    assert not target.exists()


@pytest.mark.parametrize("secret", [
    "-----BEGIN " + "PRIVATE KEY-----",
    "AKIA" + "A" * 16,
    "ghp_" + "A" * 36,
    "sk-" + "a" * 20,
    "xoxb-" + "a" * 20,
])
def test_official_baseline_patterns_scan_all_files_without_echo(project, tmp_path, secret):
    (project / "verification").mkdir()
    (project / "verification" / "README.md").write_text("Test value: " + secret)
    target = tmp_path / "review"
    with pytest.raises(packaging.PackageError, match="possible secret") as exc:
        packaging.package_submission(target, project=project)
    assert secret not in str(exc.value)
    assert not target.exists()


def test_lfs_pointer_rejected(project, tmp_path):
    (project / "source/data.bin").write_text("version https://git-lfs.github.com/spec/v1\noid sha256:test\n")
    target = tmp_path / "review"
    with pytest.raises(packaging.PackageError, match="Git LFS"):
        packaging.package_submission(target, project=project)
    assert not target.exists()


@pytest.mark.parametrize("target_type", ["file", "directory", "broken"])
def test_included_symlink_rejected(project, tmp_path, target_type):
    external = tmp_path / "external"
    if target_type == "file":
        external.write_text("must not copy")
    elif target_type == "directory":
        external.mkdir()
        (external / "private.txt").write_text("must not copy")
    (project / "source/link").symlink_to(external)
    target = tmp_path / "review"
    with pytest.raises(packaging.PackageError, match="symlinks"):
        packaging.package_submission(target, project=project)
    assert not target.exists()


@pytest.mark.parametrize("limit,value", [("MAX_FILES", 1), ("MAX_FILE_BYTES", 5), ("MAX_TOTAL_BYTES", 10)])
def test_limits_rejected_before_copy(project, tmp_path, monkeypatch, limit, value):
    monkeypatch.setattr(packaging, limit, value)
    target = tmp_path / "review"
    with pytest.raises(packaging.PackageError, match="exceeds"):
        packaging.package_submission(target, project=project)
    assert not target.exists()


def test_existing_destination_is_untouched(project, tmp_path):
    target = tmp_path / "review"
    target.mkdir()
    sentinel = target / "user-work.txt"
    sentinel.write_text("preserve me")
    with pytest.raises(packaging.PackageError, match="must not exist"):
        packaging.package_submission(target, project=project)
    assert sentinel.read_text() == "preserve me"


def test_destination_cannot_be_inside_source_or_a_symlink(project, tmp_path):
    for target in [project, project / "new" / "review"]:
        with pytest.raises(packaging.PackageError, match="outside the project"):
            packaging.package_submission(target, project=project)
    link = tmp_path / "link"
    link.symlink_to(tmp_path / "missing")
    with pytest.raises(packaging.PackageError, match="symlink"):
        packaging.package_submission(link, project=project)


def test_write_failure_removes_partial_package(project, tmp_path, monkeypatch):
    original_write = Path.write_bytes
    target = tmp_path / "review"
    count = 0

    def fail_second_file(path, content):
        nonlocal count
        count += 1
        if count == 2:
            raise OSError("injected disk failure")
        return original_write(path, content)

    monkeypatch.setattr(Path, "write_bytes", fail_second_file)
    with pytest.raises(OSError, match="injected disk failure"):
        packaging.package_submission(target, project=project)
    assert count == 2
    assert not target.exists()
    assert (project / "source/app/main.py").exists()


def test_copy_uses_the_bytes_that_passed_the_scan(project, tmp_path, monkeypatch):
    original_collect = packaging._collect

    def mutate_after_scan(path):
        checked = original_collect(path)
        (path / "source/app/main.py").write_text("changed after scan")
        return checked

    monkeypatch.setattr(packaging, "_collect", mutate_after_scan)
    target = tmp_path / "review"
    packaging.package_submission(target, project=project)
    assert (target / "source/app/main.py").read_text() == "print('review source')\n"


def committed_release(project):
    (project / "submission.json").unlink()
    config = {"schemaVersion": 1, "slug": "example-project", "apiBaseUrl": "https://example.com/v1"}
    (project / "submission-config.json").write_text(json.dumps(config))
    (project / "SUBMISSION.md").write_text("# Example capability\n")

    def git(*args):
        return subprocess.check_output(["git", *args], cwd=project, stderr=subprocess.PIPE).decode().strip()

    git("init", "-q")
    git("update-index", "--add", "source/app/main.py", "submission-config.json", "SUBMISSION.md")
    git("-c", "user.name=Packaging Test", "-c", "user.email=test@example.com",
        "-c", "commit.gpgsign=false", "commit", "-qm", "Reviewed source")
    return git("rev-parse", "HEAD")


def test_manifest_binds_actual_clean_release_without_self_reference(project, tmp_path):
    commit = committed_release(project)
    target = tmp_path / "review"
    result = packaging.package_submission(target, project=project)
    manifest = json.loads((target / "submission.json").read_text())
    assert manifest["reviewCommit"] == commit
    assert manifest["apiBaseUrl"] == "https://example.com/v1"
    assert f"Review commit: `{commit}`" in (target / "SUBMISSION.md").read_text()
    assert (project / "SUBMISSION.md").read_text() == "# Example capability\n"
    assert not (project / "submission.json").exists()
    assert "reviewCommit" not in json.loads((project / "submission-config.json").read_text())
    assert result["bytes"] == sum(path.stat().st_size for path in target.rglob("*") if path.is_file())


@pytest.mark.parametrize("change", ["tracked", "untracked"])
def test_release_manifest_rejects_uncommitted_source(project, tmp_path, change):
    committed_release(project)
    path = project / ("source/app/main.py" if change == "tracked" else "new-source.py")
    path.write_text("unreviewed source")
    target = tmp_path / "review"
    with pytest.raises(packaging.PackageError, match="clean source repository"):
        packaging.package_submission(target, project=project)
    assert not target.exists()
