"""
generated-mcp-server · generated by MCPForge 2.1.0

source API: https://petstore.swagger.io/v2
20 tools total.
this API declares auth schemes: api_key, petstore_auth.
Run:
    pip install -r requirements.txt
    fastmcp dev server.py
"""
from __future__ import annotations

import asyncio
import os
import urllib.parse
from typing import Any, Optional

import httpx
from fastmcp import FastMCP

mcp = FastMCP("generated-mcp-server")
BASE_URL = os.getenv("API_BASE_URL", "https://petstore.swagger.io/v2")



_PATH_UPLOADFILE = "/pet/{petId}/uploadImage"


def _register_uploadFile(mcp: FastMCP) -> None:
    """Call operation uploadFile (POST /pet/{petId}/uploadImage)."""

    @mcp.tool()
    async def uploadFile(petId: int) -> dict:
        """uploads an image"""
        url = BASE_URL.rstrip("/") + _PATH_UPLOADFILE
        url = url.replace("{petId}", urllib.parse.quote(str(petId)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.post(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_ADDPET = "/pet"


def _register_addPet(mcp: FastMCP) -> None:
    """Call operation addPet (POST /pet)."""

    @mcp.tool()
    async def addPet() -> dict:
        """Add a new pet to the store"""
        url = BASE_URL.rstrip("/") + _PATH_ADDPET
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.post(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_UPDATEPET = "/pet"


def _register_updatePet(mcp: FastMCP) -> None:
    """Call operation updatePet (PUT /pet)."""

    @mcp.tool()
    async def updatePet() -> dict:
        """Update an existing pet"""
        url = BASE_URL.rstrip("/") + _PATH_UPDATEPET
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.put(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_FINDPETSBYSTATUS = "/pet/findByStatus"


def _register_findPetsByStatus(mcp: FastMCP) -> None:
    """Call operation findPetsByStatus (GET /pet/findByStatus)."""

    @mcp.tool()
    async def findPetsByStatus(status: Optional[str] = None) -> dict:
        """Finds Pets by status"""
        url = BASE_URL.rstrip("/") + _PATH_FINDPETSBYSTATUS
        params: dict[str, Any] = {}
        if status is not None:
            params["status"] = status
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_FINDPETSBYTAGS = "/pet/findByTags"


def _register_findPetsByTags(mcp: FastMCP) -> None:
    """Call operation findPetsByTags (GET /pet/findByTags)."""

    @mcp.tool()
    async def findPetsByTags(tags: Optional[str] = None) -> dict:
        """Finds Pets by tags"""
        url = BASE_URL.rstrip("/") + _PATH_FINDPETSBYTAGS
        params: dict[str, Any] = {}
        if tags is not None:
            params["tags"] = tags
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GETPETBYID = "/pet/{petId}"


def _register_getPetById(mcp: FastMCP) -> None:
    """Call operation getPetById (GET /pet/{petId})."""

    @mcp.tool()
    async def getPetById(petId: int) -> dict:
        """Find pet by ID"""
        url = BASE_URL.rstrip("/") + _PATH_GETPETBYID
        url = url.replace("{petId}", urllib.parse.quote(str(petId)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_UPDATEPETWITHFORM = "/pet/{petId}"


def _register_updatePetWithForm(mcp: FastMCP) -> None:
    """Call operation updatePetWithForm (POST /pet/{petId})."""

    @mcp.tool()
    async def updatePetWithForm(petId: int) -> dict:
        """Updates a pet in the store with form data"""
        url = BASE_URL.rstrip("/") + _PATH_UPDATEPETWITHFORM
        url = url.replace("{petId}", urllib.parse.quote(str(petId)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.post(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_DELETEPET = "/pet/{petId}"


def _register_deletePet(mcp: FastMCP) -> None:
    """Call operation deletePet (DELETE /pet/{petId})."""

    @mcp.tool()
    async def deletePet(petId: int) -> dict:
        """Deletes a pet"""
        url = BASE_URL.rstrip("/") + _PATH_DELETEPET
        url = url.replace("{petId}", urllib.parse.quote(str(petId)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.delete(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GETINVENTORY = "/store/inventory"


def _register_getInventory(mcp: FastMCP) -> None:
    """Call operation getInventory (GET /store/inventory)."""

    @mcp.tool()
    async def getInventory() -> dict:
        """Returns pet inventories by status"""
        url = BASE_URL.rstrip("/") + _PATH_GETINVENTORY
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_PLACEORDER = "/store/order"


def _register_placeOrder(mcp: FastMCP) -> None:
    """Call operation placeOrder (POST /store/order)."""

    @mcp.tool()
    async def placeOrder() -> dict:
        """Place an order for a pet"""
        url = BASE_URL.rstrip("/") + _PATH_PLACEORDER
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.post(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GETORDERBYID = "/store/order/{orderId}"


def _register_getOrderById(mcp: FastMCP) -> None:
    """Call operation getOrderById (GET /store/order/{orderId})."""

    @mcp.tool()
    async def getOrderById(orderId: int) -> dict:
        """Find purchase order by ID"""
        url = BASE_URL.rstrip("/") + _PATH_GETORDERBYID
        url = url.replace("{orderId}", urllib.parse.quote(str(orderId)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_DELETEORDER = "/store/order/{orderId}"


def _register_deleteOrder(mcp: FastMCP) -> None:
    """Call operation deleteOrder (DELETE /store/order/{orderId})."""

    @mcp.tool()
    async def deleteOrder(orderId: int) -> dict:
        """Delete purchase order by ID"""
        url = BASE_URL.rstrip("/") + _PATH_DELETEORDER
        url = url.replace("{orderId}", urllib.parse.quote(str(orderId)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.delete(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_CREATEUSERSWITHLISTINPUT = "/user/createWithList"


def _register_createUsersWithListInput(mcp: FastMCP) -> None:
    """Call operation createUsersWithListInput (POST /user/createWithList)."""

    @mcp.tool()
    async def createUsersWithListInput() -> dict:
        """Creates list of users with given input array"""
        url = BASE_URL.rstrip("/") + _PATH_CREATEUSERSWITHLISTINPUT
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.post(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_GETUSERBYNAME = "/user/{username}"


def _register_getUserByName(mcp: FastMCP) -> None:
    """Call operation getUserByName (GET /user/{username})."""

    @mcp.tool()
    async def getUserByName(username: str) -> dict:
        """Get user by user name"""
        url = BASE_URL.rstrip("/") + _PATH_GETUSERBYNAME
        url = url.replace("{username}", urllib.parse.quote(str(username)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_UPDATEUSER = "/user/{username}"


def _register_updateUser(mcp: FastMCP) -> None:
    """Call operation updateUser (PUT /user/{username})."""

    @mcp.tool()
    async def updateUser(username: str) -> dict:
        """Updated user"""
        url = BASE_URL.rstrip("/") + _PATH_UPDATEUSER
        url = url.replace("{username}", urllib.parse.quote(str(username)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.put(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_DELETEUSER = "/user/{username}"


def _register_deleteUser(mcp: FastMCP) -> None:
    """Call operation deleteUser (DELETE /user/{username})."""

    @mcp.tool()
    async def deleteUser(username: str) -> dict:
        """Delete user"""
        url = BASE_URL.rstrip("/") + _PATH_DELETEUSER
        url = url.replace("{username}", urllib.parse.quote(str(username)))
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.delete(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_LOGINUSER = "/user/login"


def _register_loginUser(mcp: FastMCP) -> None:
    """Call operation loginUser (GET /user/login)."""

    @mcp.tool()
    async def loginUser(username: Optional[str] = None, password: Optional[str] = None) -> dict:
        """Logs user into the system"""
        url = BASE_URL.rstrip("/") + _PATH_LOGINUSER
        params: dict[str, Any] = {}
        if username is not None:
            params["username"] = username
        if password is not None:
            params["password"] = password
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_LOGOUTUSER = "/user/logout"


def _register_logoutUser(mcp: FastMCP) -> None:
    """Call operation logoutUser (GET /user/logout)."""

    @mcp.tool()
    async def logoutUser() -> dict:
        """Logs out current logged in user session"""
        url = BASE_URL.rstrip("/") + _PATH_LOGOUTUSER
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.get(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_CREATEUSERSWITHARRAYINPUT = "/user/createWithArray"


def _register_createUsersWithArrayInput(mcp: FastMCP) -> None:
    """Call operation createUsersWithArrayInput (POST /user/createWithArray)."""

    @mcp.tool()
    async def createUsersWithArrayInput() -> dict:
        """Creates list of users with given input array"""
        url = BASE_URL.rstrip("/") + _PATH_CREATEUSERSWITHARRAYINPUT
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.post(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}


_PATH_CREATEUSER = "/user"


def _register_createUser(mcp: FastMCP) -> None:
    """Call operation createUser (POST /user)."""

    @mcp.tool()
    async def createUser() -> dict:
        """Create user"""
        url = BASE_URL.rstrip("/") + _PATH_CREATEUSER
        params: dict[str, Any] = {}
        json_body = None
        last_err: Optional[Exception] = None
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=20, follow_redirects=True) as c:
                    r = await c.post(
                        url, params=params or None, json=json_body, headers=HEADERS
                    )
                return {
                    "status_code": r.status_code,
                    "url": str(r.url),
                    "body": r.text[:4000],
                }
            except httpx.TransportError as e:
                last_err = e
                await asyncio.sleep(0.4 * (attempt + 1))
        return {"error": f"{type(last_err).__name__}: {last_err}"}

_register_uploadFile(mcp)
_register_addPet(mcp)
_register_updatePet(mcp)
_register_findPetsByStatus(mcp)
_register_findPetsByTags(mcp)
_register_getPetById(mcp)
_register_updatePetWithForm(mcp)
_register_deletePet(mcp)
_register_getInventory(mcp)
_register_placeOrder(mcp)
_register_getOrderById(mcp)
_register_deleteOrder(mcp)
_register_createUsersWithListInput(mcp)
_register_getUserByName(mcp)
_register_updateUser(mcp)
_register_deleteUser(mcp)
_register_loginUser(mcp)
_register_logoutUser(mcp)
_register_createUsersWithArrayInput(mcp)
_register_createUser(mcp)

if __name__ == "__main__":
    mcp.run()
